<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/Kemilly_Mota/6aula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random as rd
import numpy as np

#geração de números entre 150 e 209
height = range(150,210)

#geração de número entre 50 e 149
weight = range(50,150)


In [ ]:
#amostra randomica de 20 números de height
height = rd.sample(height,20)

#amostra ramdomica de 20 números de weight
weight = rd.sample(weight,20)

In [ ]:
#covertendo height em array e normalizando, fazendo a multiplicação por 0.01
height_array = np.array(height)*0.01
weight_array = np.array(weight)
print(height_array)
print(weight_array)

[1.63 1.56 2.03 1.52 1.53 2.08 1.9  1.99 1.72 1.5  1.96 1.81 1.75 1.64
 1.6  1.57 1.97 1.93 2.05 2.02]
[ 74 108  89  56 146 134 121 120 133 125  63  76  69  87  50  79 104 102
 109  54]


In [ ]:
#cálculo do BMI
bmi = weight_array / height_array**2
bmi

array([27.85200798, 44.37869822, 21.59722391, 24.23822715, 62.36917425,
       30.97263314, 33.51800554, 30.30226509, 44.95673337, 55.55555556,
       16.39941691, 23.19831507, 22.53061224, 32.34681737, 19.53125   ,
       32.04998174, 26.7979077 , 27.38328546, 25.9369423 , 13.23399667])

In [ ]:
#verificação onde bmi é menor que 21
light = bmi < 21
light

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False,  True])

In [ ]:
#exibição dos valores de bmi com valor menor que 21
print(bmi[light])

[16.39941691 19.53125    13.23399667]


In [ ]:
#print os elementos de weight_array do index 8 até o index 15, incluindo o index 15
print(weight_array[8:16])

[133 125  63  76  69  87  50  79]


In [ ]:
#print os elementos do height_array doo index 11 até o index 19,  incluindo o index 19
print(height_array[11:20])

[1.81 1.75 1.64 1.6  1.57 1.97 1.93 2.05 2.02]
