<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/Kemilly_Mota/atividadenumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#exemplo 1. Propriedades de Arrays

import numpy as np

a = np.arange(15).reshape(3, 5)
print("Array a:\n", a)
print("Shape:", a.shape)
print("Número de dimensões (ndim):", a.ndim)
print("Tipo de dado (dtype.name):", a.dtype.name)
print("Tamanho de cada item (bytes):", a.itemsize)
print("Número total de elementos:", a.size)
print("Tipo do objeto:", type(a))

b = np.array([6, 7, 8])
print("\nArray b:", b)
print("Tipo de b:", type(b))

Array a:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Shape: (3, 5)
Número de dimensões (ndim): 2
Tipo de dado (dtype.name): int64
Tamanho de cada item (bytes): 8
Número total de elementos: 15
Tipo do objeto: <class 'numpy.ndarray'>

Array b: [6 7 8]
Tipo de b: <class 'numpy.ndarray'>


In [ ]:
#exemplo 2. Tipos de Dados

import numpy as np

a = np.array([2, 3, 4])
print("Array a:", a)
print("Tipo de dados de a:", a.dtype)

b = np.array([1.2, 3.5, 5.1])
print("Array b:", b)
print("Tipo de dados de b:", b.dtype)


Array a: [2 3 4]
Tipo de dados de a: int64
Array b: [1.2 3.5 5.1]
Tipo de dados de b: float64


In [ ]:
#exemplo 3. Criação de Arrays e Tipagem Explícita

import numpy as np

# a = np.array(1, 2, 3, 4)  # ERRADO

# Exemplo correto
a = np.array([1, 2, 3, 4])
print("Array a:", a)

b = np.array([(1.5, 2, 3), (4, 5, 6)])
print("\nArray b:\n", b)

c = np.array([[1, 2], [3, 4]], dtype=complex)
print("\nArray c (complexo):\n", c)


Array a: [1 2 3 4]

Array b:
 [[1.5 2.  3. ]
 [4.  5.  6. ]]

Array c (complexo):
 [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [ ]:
#exemplo 4. Criação de Arrays com Formas e Tipos Específicos

import numpy as np
from numpy import pi

a = np.zeros((3, 4))
print("zeros:\n", a)

b = np.ones((2, 3, 4), dtype=np.int16)
print("\nones (int16):\n", b)

c = np.empty((2, 3))
print("\nempty (valores aleatórios):\n", c)

zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones (int16):
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

empty (valores aleatórios):
 [[1.5 2.  3. ]
 [4.  5.  6. ]]


In [ ]:
#exemplo 5.Impressão de Arrays: 1D, 2D e 3D

# Sequência de 10 a 30 com passo 5
seq1 = np.arange(10, 30, 5)
print("\narange(10, 30, 5):", seq1)

seq2 = np.arange(0, 2, 0.3)
print("\narange(0, 2, 0.3):", seq2)

lin = np.linspace(0, 2, 9)
print("\nlinspace(0, 2, 9):", lin)

x = np.linspace(0, 2 * pi, 100)
f = np.sin(x)
print("\nPrimeiros 5 valores de sin(x):", f[:5])



arange(10, 30, 5): [10 15 20 25]

arange(0, 2, 0.3): [0.  0.3 0.6 0.9 1.2 1.5 1.8]

linspace(0, 2, 9): [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

Primeiros 5 valores de sin(x): [0.         0.06342392 0.12659245 0.18925124 0.25114799]


In [ ]:
#exemplo 6. Impressão de Arrays Grandes (completa)

# 1D
a = np.arange(6)
print("\nArray 1D:", a)

# 2D
b = np.arange(12).reshape(4, 3)
print("\nArray 2D:\n", b)

# 3D
c = np.arange(24).reshape(2, 3, 4)
print("\nArray 3D:\n", c)



Array 1D: [0 1 2 3 4 5]

Array 2D:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Array 3D:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
#exemplo 7

import sys

big = np.arange(10000).reshape(100, 100)
print("\nArray grande (forma reduzida):\n", big)

np.set_printoptions(threshold=sys.maxsize)



Array grande (forma reduzida):
 [[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [ ]:
#exemplo 8. Operações Aritméticas com Arrays

import numpy as np

a = np.array([20, 30, 40, 50])
b = np.arange(4)
print("a - b:", a - b)
print("b ** 2:", b**2)
print("10 * np.sin(a):", 10 * np.sin(a))
print("a < 35:", a < 35)


a - b: [20 29 38 47]
b ** 2: [0 1 4 9]
10 * np.sin(a): [ 9.12945251 -9.88031624  7.4511316  -2.62374854]
a < 35: [ True  True False False]


In [ ]:
#exemplo 9. Produto de Matrizes vs Produto Elementwise

A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

print("Produto elementwise A * B:\n", A * B)
print("Produto matricial A @ B:\n", A @ B)
print("Produto com .dot():\n", A.dot(B))

Produto elementwise A * B:
 [[2 0]
 [0 4]]
Produto matricial A @ B:
 [[5 4]
 [3 4]]
Produto com .dot():
 [[5 4]
 [3 4]]


In [ ]:
#exemplo 10. Operações In-Place e Upcasting

rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

a *= 3
print("a após *= 3:\n", a)

b += a
print("b após b += a:\n", b)



a após *= 3:
 [[3 3 3]
 [3 3 3]]
b após b += a:
 [[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


In [ ]:
#exemplo 11. Upcasting e Operações com Tipos Diferentes

from numpy import pi

a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)

print("b.dtype:", b.dtype.name)
c = a + b
print("c:", c)
print("c.dtype:", c.dtype.name)

d = np.exp(c * 1j)
print("d (números complexos):", d)
print("d.dtype:", d.dtype.name)


b.dtype: float64
c: [1.         2.57079633 4.14159265]
c.dtype: float64
d (números complexos): [ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
d.dtype: complex128


In [ ]:
#exemplo 12. Operações Estatísticas com Arrays

a = rg.random((2, 3))
print("Array aleatório:\n", a)
print("Soma:", a.sum())
print("Mínimo:", a.min())
print("Máximo:", a.max())


Array aleatório:
 [[0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]]
Soma: 3.1057109529998157
Mínimo: 0.027559113243068367
Máximo: 0.8277025938204418


In [ ]:
#exemplo 13.  Operações por Eixo

b = np.arange(12).reshape(3, 4)
print("Array b:\n", b)

print("Soma por coluna (axis=0):", b.sum(axis=0))
print("Mínimo por linha (axis=1):", b.min(axis=1))
print("Soma cumulativa por linha:", b.cumsum(axis=1))


Array b:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Soma por coluna (axis=0): [12 15 18 21]
Mínimo por linha (axis=1): [0 4 8]
Soma cumulativa por linha: [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [ ]:
#exemplo 14. Funções Universais

B = np.arange(3)
C = np.array([2., -1., 4.])

print("exp(B):", np.exp(B))
print("sqrt(B):", np.sqrt(B))
print("add(B, C):", np.add(B, C))


exp(B): [1.         2.71828183 7.3890561 ]
sqrt(B): [0.         1.         1.41421356]
add(B, C): [2. 0. 6.]


In [ ]:
#exemplo 15.Indexação, Fatiamento e Iteração

a = np.arange(10) ** 3
print("a:", a)
print("a[2]:", a[2])
print("a[2:5]:", a[2:5])

a[:6:2] = 1000
print("a após atribuição:", a)

print("a[::-1] (reverso):", a[::-1])

# Iterando com raiz cúbica
for i in a:
    print(i ** (1/3.))

a: [  0   1   8  27  64 125 216 343 512 729]
a[2]: 8
a[2:5]: [ 8 27 64]
a após atribuição: [1000    1 1000   27 1000  125  216  343  512  729]
a[::-1] (reverso): [ 729  512  343  216  125 1000   27 1000    1 1000]
9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [ ]:
#exemplo 16. Multidimensionais com 'fromfunction' e Indexação Avançada

def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)
print("fromfunction:\n", b)

print("Elemento [2, 3]:", b[2, 3])
print("Coluna 1:", b[:, 1])
print("Linhas 1 a 2:\n", b[1:3, :])
print("Última linha:", b[-1])

fromfunction:
 [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
Elemento [2, 3]: 23
Coluna 1: [ 1 11 21 31 41]
Linhas 1 a 2:
 [[10 11 12 13]
 [20 21 22 23]]
Última linha: [40 41 42 43]


In [ ]:
#exemplo 17. Indexação com reticências

c = np.array([
    [[0, 1, 2], [10, 12, 13]],
    [[100, 101, 102], [110, 112, 113]]
])

print(c[1, ...])
print(c[..., 2])

[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]


In [ ]:
#exemplo 18. Iteração em arrays multidimensionais

for row in c:
    print(row)  # Itera sobre o primeiro eixo (linhas)

for element in c.flat:
    print(element)  # Itera sobre todos os elementos

[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]
0
1
2
10
12
13
100
101
102
110
112
113


In [ ]:
#exemplo 19. Manipulação de Forma (Shape)

a = np.floor(10 * np.random.default_rng().random((3, 4)))

print(a.shape)
print(a.ravel())
print(a.reshape(6, 2))
print(a.T)
a.resize((2, 6))
print(a.reshape(3, -1))

(3, 4)
[9. 5. 4. 9. 3. 5. 4. 8. 1. 7. 9. 7.]
[[9. 5.]
 [4. 9.]
 [3. 5.]
 [4. 8.]
 [1. 7.]
 [9. 7.]]
[[9. 3. 1.]
 [5. 5. 7.]
 [4. 4. 9.]
 [9. 8. 7.]]
[[9. 5. 4. 9.]
 [3. 5. 4. 8.]
 [1. 7. 9. 7.]]


In [ ]:
#exemplo 20.  Empilhamento de arrays

a = np.floor(10 * np.random.random((2, 2)))
b = np.floor(10 * np.random.random((2, 2)))

print(np.vstack((a, b)))  # Empilha verticalmente
print(np.hstack((a, b)))  # Empilha horizontalmente

a1 = np.array([4., 2.])
b1 = np.array([3., 8.])
print(np.column_stack((a1, b1)))
print(np.hstack((a1, b1)))

from numpy import newaxis
print(np.column_stack((a1[:, newaxis], b1[:, newaxis])))

In [ ]:
#exemplo 21. Dividindo arrays

a = np.floor(10 * np.random.random((2, 12)))

print(np.hsplit(a, 3))         # Divide em 3 partes iguais
print(np.hsplit(a, (3, 4)))    # Divide após as colunas 3 e 4

[array([[6., 3., 9., 8.],
       [7., 0., 5., 8.]]), array([[2., 0., 2., 5.],
       [3., 8., 5., 9.]]), array([[4., 7., 1., 4.],
       [7., 4., 2., 2.]])]
[array([[6., 3., 9.],
       [7., 0., 5.]]), array([[8.],
       [8.]]), array([[2., 0., 2., 5., 4., 7., 1., 4.],
       [3., 8., 5., 9., 7., 4., 2., 2.]])]


Copias e visões

In [ ]:
#exemplo 22. Sem cópia (atribuição direta)

a = np.arange(12).reshape(3, 4)
b = a
print(b is a)  # True

True


In [ ]:
#exemplo 23. Visão
c = a.view()
c[0, 1] = 1234
print(a)  # Muda também o original


[[   0 1234    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]


In [ ]:
#exemplo 24. Copia profunda
d = a.copy()
d[0, 0] = 9999
print(a)  # Não muda


[[   0 1234    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]
