<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/levi_nascimento/Atividade_casa_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Página 6

In [5]:
import numpy as np
# a = np.arange >> cria um array com os valores de 0 a 14
# a = a.reshape(3, 5) >> redimensiona para 3 linhas e 5 colunas

a = np.arange(15).reshape(3, 5)
print(a)

#a.shape retorna uma tupla com as dimensões do array
a.shape
print(a.shape)
#a.ndim retorna o número de dimensões
a.ndim
print(a.ndim)
#a.size retorna o número de elementos do array
a.size
print(a.size)

print(type(a))

b = np.array([6, 7, 8])
print(b)
print(type(b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
15
<class 'numpy.ndarray'>
[6 7 8]
<class 'numpy.ndarray'>


Página 7

In [8]:
a = np.array([2, 3, 4])
print(a)

# detecta que são inteiros e atribui tipo (int64)
a.dtype
print(a.dtype)

# detecta float e atribui tipo (float64)
b = np.array([1.2, 3.5, 5.1])
print(b.dtype)


[2 3 4]
int64
float64


In [9]:
#demonstra um erro comum ao passar múltiplos argumentos separados
# em vez de uma lista
a = np.array(1, 2, 3, 4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [10]:
a = np.array([1, 2, 3, 4])
#forma certa

In [12]:
 #cria arrays multidimensionais
 b = np.array([(1.5, 2, 3), (4, 5, 6)])
 print(b)
 #uma matriz 2x3

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [13]:
#Definir explicitamente o tipo de dado (dtype)
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)
#array de números complexos

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [14]:
#Criar arrays com valores predefinidos
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# array 3D (2 blocos de 3 linhas x 4 colunas) preenchidos com 1 e tipo int16
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
#Cria uma array sem inicializar os valores (fica com valores aleatórios da memória - não confiáveis)
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Página 8

In [19]:
#Início, fim, passo (Cria uma array começando de início até antes de fim, com um valor de incremento (passo))
#Exemplo de número inteiro
print(np.arange(10, 30, 5))
#exemplo de número decimal
print(np.arange(0, 2, 0.3))

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [20]:
from numpy import pi
#Gerar número exato de valores igualmente espaçados entre dois limites np.linspace(inicio, fim, quantidade)
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [23]:
# 100 pontos de 0 a 2π
x = np.linspace(0, 2 * pi, 100)
# calcula seno de cada ponto
f = np.sin(x)

In [25]:
#Exemplo array 1D
a = np.arange(6)
print(a)
#Exemplo array 2D
b = np.arange(12).reshape(4, 3)
print(b)
#exemplo array 3D
c = np.arange(24).reshape(2, 3, 4)
print(c)
# Cada “bloco” representa a última e penúltima dimensões.


[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Página 9

In [29]:
#impressão de arrays grandes
#Por padrão, o NumPy exibe arrays grandes de forma abreviada para não poluir o terminal.
print(np.arange(10000))

#Exemplo de array 2D
print(np.arange(10000).reshape(100, 100))


[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [ ]:
#se quiser que o numpy mostre tudo
import sys
np.set_printoptions(threshold=sys.maxsize)

In [36]:
#Operações básicas com array
#No NumPy, os operadores aritméticos funcionam elemento por elemento (elementwise).
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(b)

c = a- b
print(c)
#Cada elemento de b foi subtraído do correspondente de a.

# Potenciação
print(b**2)

#Funções matemáticas elementwise:
print(10 * np.sin(a))
#Calcula o seno de cada valor de a e multiplica por 10.

#Comparação elemento a elemento:
a < 35

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


array([ True,  True, False, False])

In [38]:
A = np.array([[1, 1],
 [0, 1]])


B = np.array([[2, 0],
 [3, 4]])

A * B

array([[2, 0],
       [0, 4]])

In [39]:
#Produto de matrizes (matricial) — com @ ou np.dot()

print(A @ B)
print(np.dot(A, B))

[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


Página 10

In [44]:
#No NumPy, algumas operações como += e
#*= modificam diretamente o array original, sem criar um novo.

rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

a *= 3
print(a)

b += a
print(b)

#b não é automaticamente  convertido para o tipo
print(a += b)

SyntaxError: invalid syntax (<ipython-input-44-63c11e0c6dad>, line 14)

In [49]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
print(b.dtype.name)

c = a + b
print(c)
#a é inteiro, b é float64, o resultado (c) será float64.


# np.exp(c * 1j) calcula e^ix (forma de Euler).
d = np.exp(c * 1j)
print(d)
d.dtype.name

float64
[1.         2.57079633 4.14159265]
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]


'complex128'

In [54]:
#Funções como .sum(), .min(), .max() são métodos aplicados a arrays NumPy.
a = rg.random((2, 3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[0.51606859 0.11586561 0.62348976]
 [0.77668311 0.6130033  0.9172977 ]]
3.5624080737423904
0.11586561247077032
0.9172977047909027


Página 11

In [55]:
#Operações com o parâmetro axis
#Por padrão, operações como sum(), min() ou max()
#são aplicadas a todos os elementos do array, como se fosse uma lista única.

#Mas, usando o argumento axis, você consegue especificar se quer operar:

#por colunas (axis=0)

#por linhas (axis=1)

b = np.arange(12).reshape(3, 4)
print(b)
#Soma por coluna:
print(b.sum(axis=0))
#Mínimo por linha:
print(b.min(axis=1))
#Soma acumulada por linha:
print(b.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [58]:
#As ufuncs são funções matemáticas prontas no NumPy
#que operam elemento a elemento dos arrays, retornando um novo array.

b = np.arange(3)
print(b)
#Exponencial
print(np.exp(b))
#Raiz Quadrada
print(np.sqrt(b))

#Soma elemento a elemento com outro array:
c = np.array([2., -1., 4.])
np.add(b, c)

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


array([2., 0., 6.])

Página 12

Indexação, fatiamento e iteração em arrays NumPy

Arrays NumPy funcionam de forma semelhante a listas Python em termos de indexação, fatiamento e iteração — mas com alguns recursos adicionais bem interessantes.

In [ ]:
#Indexação e fatiamento em 1D
#Um array unidimensional pode ser indexado e fatiado como uma lista:

In [65]:
a = np.arange(10)**3
print(a)

#Acessar elemento:
print(a[2])

#Fatiar:
print(a[2:5])

#Alterar múltiplos valores via fatiamento:
a[:6:2] = 1000
print(a)

#Inverter array:
print(a[::-1])

#Iterar sobre os elementos:

for i in a:
    print(i**(1/3))

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[1000    1 1000   27 1000  125  216  343  512  729]
[ 729  512  343  216  125 1000   27 1000    1 1000]
9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


Indexação e fatiamento em arrays multidimensionais

Em arrays multidimensionais, você pode usar uma tupla de índices:

In [72]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)
print(b)

#Acessar elemento [linha 2, coluna 3]:
print(b[2, 3])

b[0:5, 1]

#Selecionar a segunda coluna inteira:
print(b[:, 1])
#Selecionar linhas 1 e 2, todas as colunas:
print(b[1:3, :])
#Última linha do array:
print(b[-1])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43]


Página 13

 Acessos com ... (reticências) em arrays multidimensionais NumPy

Em NumPy, o operador ... (ellipsis) serve como um atalho para preencher com : todas as dimensões restantes que não foram especificadas na indexação.

Como funciona:
Se um array tem 5 eixos (dimensões), por exemplo:

x[1, 2, ...] → equivale a x[1, 2, :, :, :]

x[..., 3] → equivale a x[:, :, :, :, 3]

x[4, ..., 5, :] → equivale a x[4, :, :, 5, :]

Isso deixa o código mais compacto e legível, principalmente com arrays de alta dimensão.

In [75]:
#Exemplo prático com array 3D:

c = np.array([
    [[  0,   1,   2],
     [ 10,  12,  13]],

    [[100, 101, 102],
     [110, 112, 113]]
])

print(c.shape)

#Acessos com reticências:
print(c[1, ...]) #mesmo que c[1, :, :]

c[..., 2]   # mesmo que c[:, :, 2]

(2, 2, 3)
[[100 101 102]
 [110 112 113]]


array([[  2,  13],
       [102, 113]])

Iteração em arrays multidimensionais
Quando iteramos sobre um array multidimensional, o loop percorre a primeira dimensão (o primeiro eixo) e retorna arrays de dimensão reduzida.

In [79]:
for row in b:
    print(row)

#Se quiser iterar sobre todos os elementos individualmente, use .flat:
for element in b.flat:
    print(element)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


Página 14 2.3.1



 Formas e Transformações de Arrays no NumPy
A forma (shape) de um array indica quantos elementos há em cada eixo (dimensão).

In [80]:
a = np.floor(10 * rg.random((3, 4)))
print(a)
print(a.shape)

[[0. 5. 4. 0.]
 [6. 8. 5. 2.]
 [8. 5. 5. 7.]]
(3, 4)


Mudança de forma sem alterar o conteúdo
NumPy permite várias maneiras de reorganizar os dados:

In [89]:
#ravel(): transforma o array em 1D (flatten)
print(a.ravel())
#reshape(): retorna uma nova visão do array com nova forma
print(a.reshape(6, 2))
#transposição (troca linhas por colunas)
print(a.T)

print(a.T.shape)
print(a.shape)
print(a)
#Diferente de reshape(), resize() altera o array original:
a.resize((2, 6))
print(a)

[0. 5. 4. 0. 6. 8. 5. 2. 8. 5. 5. 7.]
[[0. 5.]
 [4. 0.]
 [6. 8.]
 [5. 2.]
 [8. 5.]
 [5. 7.]]
[[0. 5.]
 [5. 2.]
 [4. 8.]
 [0. 5.]
 [6. 5.]
 [8. 7.]]
(6, 2)
(2, 6)
[[0. 5. 4. 0. 6. 8.]
 [5. 2. 8. 5. 5. 7.]]
[[0. 5. 4. 0. 6. 8.]
 [5. 2. 8. 5. 5. 7.]]


In [90]:
a.reshape(3,-1)

array([[0., 5., 4., 0.],
       [6., 8., 5., 2.],
       [8., 5., 5., 7.]])

Página 15 2.3.2

In [92]:
#vstack() — empilha verticalmente (primeiro eixo)
#Junta arrays adicionando-os como novas linhas.
a = np.floor(10 * rg.random((2, 2)))
b = np.floor(10 * rg.random((2, 2)))

print(np.vstack((a, b)))

#hstack() — empilha horizontalmente (segundo eixo)
#Junta arrays lado a lado.
print(np.hstack((a, b)))



[[8. 8.]
 [8. 4.]
 [2. 0.]
 [6. 7.]]
[[8. 8. 2. 0.]
 [8. 4. 6. 7.]]


In [97]:
#newaxis — cria nova dimensão (útil para empilhamento)
from numpy import newaxis
print(np.column_stack((a, b)))

a = np.array([4., 2.])
b = np.array([3., 8.])
print(np.column_stack((a, b)) )

print(np.hstack((a, b)))
print(np.column_stack((a, b)) )

print(a[:, newaxis])
print(np.column_stack((a[:, newaxis], b[:, newaxis])))
print(np.hstack((a[:, newaxis], b[:, newaxis])))


[[4. 3.]
 [2. 8.]]
[[4. 3.]
 [2. 8.]]
[4. 2. 3. 8.]
[[4. 3.]
 [2. 8.]]
[[4.]
 [2.]]
[[4. 3.]
 [2. 8.]]
[[4. 3.]
 [2. 8.]]


In [98]:
#r_ e c_ — atalhos convenientes para empilhar números e arrays
#permitem usar notação tipo fatia :
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

PÁGINA 16 2.3.3

Dividindo Arrays no NumPy com hsplit()
A função hsplit() permite dividir um array ao longo do eixo horizontal (segundo eixo).
Você pode dividir:

Em um número igual de partes

Ou especificar os índices das colunas onde as divisões devem acontecer.

In [99]:
#Dividir em partes iguais
a = np.floor(10 * rg.random((2, 12)))
print(a)

#Dividir em 3 partes horizontais:
print(np.hsplit(a, 3))

#Dividir em posições específicas
#Você pode informar as posições das colunas onde deseja cortar:
print(np.hsplit(a, (3, 4)))

[[8. 2. 2. 6. 8. 9. 1. 4. 8. 4. 5. 0.]
 [6. 9. 8. 8. 6. 2. 7. 2. 8. 0. 8. 1.]]
[array([[8., 2., 2., 6.],
       [6., 9., 8., 8.]]), array([[8., 9., 1., 4.],
       [6., 2., 7., 2.]]), array([[8., 4., 5., 0.],
       [8., 0., 8., 1.]])]
[array([[8., 2., 2.],
       [6., 9., 8.]]), array([[6.],
       [8.]]), array([[8., 9., 1., 4., 8., 4., 5., 0.],
       [6., 2., 7., 2., 8., 0., 8., 1.]])]


PÁGINA 17 2.4.1

In [101]:
#Simples atribuições não criam novas cópias do array nem de seus dados.
a = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])

b = a
print(b is a)
#a e b são nomes diferentes para o mesmo objeto na memória.

True


In [106]:
def f(x):
  print(id(x))
print(id(a))
print(f(a))

135664726335312
135664726335312
None


Diferentes objetos podem compartilhar os mesmos dados. A função view() cria um novo array com o mesmo conteúdo.

In [109]:
c = a.view()
print(c is a)
print(c.base is a)
print(c.flags.owndata)

#Se alterar a forma de c, isso não afeta a.
#Mas se alterar os dados, ambos são afetados.
c = c.reshape((2, 6))
a.shape

c[0, 4] = 1234
print(a)
#a também terá esse valor alterado, porque compartilham os mesmos dados.

False
True
False
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [110]:
#Fatiamentos em NumPy retornam views, não cópias.

s = a[:, 1:3]
s[:] = 10
print(a)
#Isso modifica a diretamente.

[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


Página 18 2.4.3

In [111]:
#Para garantir uma cópia independente, use copy()
d = a.copy()
print(d is a)
print(d.base is a)
print(d.flags.owndata)
# Agora, mudanças em d não afetam a, pois os dados são independentes.

False
False
True


In [114]:
a = np.arange(int(1e8))   # Array grande com 100 milhões de elementos
b = a[:100].copy()  # Apenas uma view dos primeiros 100 elementos, # Faz uma cópia independente dos dados
del a  # Tentativa de liberar a memória # Agora a memória de `a` será liberada, pois b é independente
