<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/Francisco_Gomes/atividade_10_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["bedroom", 10.75],
         ["bathoroom", 9.50]]

for comodo, area in house:
  print("the", comodo, "is", area, "sqm")

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathoroom is 9.5 sqm


In [2]:
world = {"afghanistan": 30.55,
         "albania": 2.77,
         "algeria": 39.21}

for key, value in world.items() :
  print(key + " -- " + str(value))

afghanistan -- 30.55
albania -- 2.77
algeria -- 39.21


In [3]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
for val in bmi:
  print(val)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


In [4]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas = np.array([np_height, np_weight])
for val in meas :
  print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [5]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas = np.array([np_height, np_weight])
for val in np.nditer(meas) :
  print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


In [10]:
#com o auxilio do loop for proporcione a seguinte saída
europe = {"spain": "madrid", "france": "paris", "germany": "berlim",
          "norway": "oslo", "italy": "rome", "poland": "warsaw",
          "austria": "vienna"}

for país, capital in europe:
  print("the capital of", país, "is", capital)

In [8]:
#mostar cada linha separada
import numpy as np
np_height = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_weight = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
meas = np.array([np_height, np_weight])
for val in meas :
  print(val)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [9]:
#mostrar cada elemento em cada linha
np_height = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_weight = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
meas = np.array([np_height, np_weight])
meas = np.array([np_height, np_weight])
for val in np.nditer(meas) :
  print(val)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
