<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/kauan_lima/atividades30_05_pt2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pratique

In [1]:
import random as rd
import numpy as np

height = range(150,210)
height

range(150, 210)

In [2]:
weight = range(50,100)
weight

range(50, 100)

In [3]:
height = rd.sample(height,20)
height

[160,
 156,
 169,
 206,
 189,
 207,
 174,
 192,
 208,
 165,
 186,
 163,
 193,
 209,
 171,
 196,
 200,
 183,
 199,
 204]

In [4]:
weight = rd.sample(weight,20)
weight

[50,
 73,
 85,
 60,
 75,
 72,
 94,
 61,
 89,
 93,
 86,
 76,
 97,
 82,
 69,
 65,
 78,
 83,
 77,
 70]

In [5]:
height_array = np.array(height)*0.01
height_array

array([1.6 , 1.56, 1.69, 2.06, 1.89, 2.07, 1.74, 1.92, 2.08, 1.65, 1.86,
       1.63, 1.93, 2.09, 1.71, 1.96, 2.  , 1.83, 1.99, 2.04])

In [6]:
weight_array = np.array(weight)*0.01
weight_array

array([0.5 , 0.73, 0.85, 0.6 , 0.75, 0.72, 0.94, 0.61, 0.89, 0.93, 0.86,
       0.76, 0.97, 0.82, 0.69, 0.65, 0.78, 0.83, 0.77, 0.7 ])

In [7]:
#calculo bmi
import random as rd
import numpy as np

height = (1.73, 1.68, 1.71, 1.89, 1.79)
weight = (65.4, 59.2, 63.6, 88.4, 68.7)

np_height = np.array(height)
np_weight = np.array(weight)

bmi = np_weight / (np_height**2)
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [11]:
import numpy as np

height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]


np_height = np.array(height)
np_weight = np.array(weight)

# Calculando BMI
bmi = np_weight / (np_height ** 2)

# Verificando quais valores são menores que 21
light = bmi < 21
light
# Mostrando resultado
for i in range(len(bmi)):
     print(f"Pessoa {i+1}: BMI = {bmi[i]:.2f} {light[i]}")

Pessoa 1: BMI = 21.85 False
Pessoa 2: BMI = 20.98 True
Pessoa 3: BMI = 21.75 False
Pessoa 4: BMI = 24.75 False
Pessoa 5: BMI = 21.44 False


In [12]:
import random as rd
import numpy as np

height = (1.73, 1.68, 1.71, 1.89, 1.79)
weight = (65.4, 59.2, 63.6, 88.4, 68.7)

np_height = np.array(height)
np_weight = np.array(weight)

print(np_height[8:15])
print(np_weight[11:19])

[]
[]


In [13]:
import numpy as np
height = (1.73, 1.68, 1.71, 1.89, 1.79)
weight = (65.4, 59.2, 63.6, 88.4, 68.7)

weight_array = weight

print(weight_array[8:16])

height_array = height
print(height_array[11:19])

()
()
