<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/Francisco_Gomes/atividade_04_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

bmi = np_height / np_weight * 2
bmi


array([0.0529052 , 0.05675676, 0.05377358, 0.04276018, 0.05211063])

In [10]:
bmi > 23

array([False, False, False, False, False])

In [11]:
bmi[bmi > 23]

array([], dtype=float64)

In [19]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

bmi > 30
print("você não está com o peso adequado")
bmi < 30
print("você está com o peso adequado")

você não está com o peso adequado
você está com o peso adequado


In [25]:
#true
5 == 2 + 3
#false
32 == 4* 9

False

In [20]:
#verificado a multiplicação
-5 * 15

-75

In [21]:
#verificando se a strings são iguais
"pyscript" == "pyscript"

True

In [23]:
#verificando se true é igual a um
"true" == 1

False

In [31]:
#quais elementos são maiores que 18
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])
print(my_house > 18)

[False  True False False]


In [32]:
#elementos de my_house que são menor que your_house
print(my_house < your_house)

[False  True  True False]


In [35]:
#retornar false
x = 10
x > 9 and x < 8

False

In [38]:
#retornar false
y = 8
y < 7 or y > 15

False

In [44]:
# 1 questão
my_kitchen = 18.0
your_kitchen = 14.0

18.0 > 10.0 and 18.0 < 17.0

False

In [45]:
# segunda questão
18.0 < 14 and 18.0 <17

False

In [46]:
# terceira questão
36.0 < 42.0

True

In [47]:
# quarta questão
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

np.logical_and( my_house > 18, my_house < 10)

array([False, False, False, False])

In [48]:
# quinta questão
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

np.logical_and(my_house < 11, your_house < 11)

array([False, False, False,  True])

In [52]:
#condições IF and ELSE
z = 6
if z % 2 == 0 : #false
  print("z é par")
else :
  print("z é impar")

z é par


In [54]:
z = 3
if z % 2 == 0 :
  print('z é divisível por 2')
elif z % 3 == 0 :
  print("z é divisível por 3")
else :
  print("z não é divisível nem por 2 e nem por 3")

z é divisível por 3


In [60]:
romm = "kit"
area = "14.0"

if 14 > 15 :
  print("big place")
else:
  print("pretty small")

pretty small
