<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/gabriel_coelho/atividade5%20-%20Documenta%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ATIVIDADE P/ CASA

#2.2 O BÁSICO

**2.2.1 UM EXEMPLO**


In [140]:
#criando um array 'a' de 0 a 14 organizado em uma matriz 3x5
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [149]:
#atributos de 'a'
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)

(3, 5)
2
int64
8
15


In [148]:
#tipo de 'a'
print(type(a))

<class 'numpy.ndarray'>


In [153]:
#criando um array 'b'
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [151]:
#tipo de 'b'
print(type(b))

<class 'numpy.ndarray'>


**2.2.2 CRIAÇÃO DE ARRAY**

In [154]:
import numpy as np

#criando um array 'a'
a = np.array([2, 3, 4])
a

#printando o tipo de dado do array 'a'
print(a.dtype)

#criando um array 'b'
b = np.array([1.2, 3.5, 5.1])
b

#printando o tipo de dado do array 'b'
print(b.dtype)

int64
float64


*Um erro frequente consiste em chamar array com vários argumentos, em vez de fornecer uma única sequência como
argumento:

In [ ]:
a = np.array(1, 2, 3, 4) #WRONG
a = np.array([1, 2, 3, 4]) #RIGHT

*O tipo da matriz também pode ser especificado explicitamente no momento da criação:

In [ ]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

*A função ZEROS cria uma matriz cheia de 0s, a função ONES cria uma matriz cheia de 1s e a função EMPTY cria uma matriz cujo conteúdo inicial é aleatório e depende do estado da memória:

In [156]:
#função ZEROS
zeros = np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [157]:
#função ONES
ones = np.ones((2, 3, 4), dtype=np.int16)
ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [162]:
#função EMPTY
empty = np.empty((2, 3))
empty

array([[1., 6., 5.],
       [1., 1., 5.]])

*Para criar sequências de números, o NumPy fornece a função ARANGE que é análoga ao intervalo interno do Python, mas retorna uma matriz.

In [164]:
a = np.arange(10, 30, 5)
a

array([10, 15, 20, 25])

In [165]:
b = np.arange(0, 2, 0.3) #aceita argumentos float
b

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

*Quando um intervalo é usado com argumentos de ponto flutuante, geralmente não é possível prever o número de
elementos obtidos, devido à precisão finita do ponto flutuante. Por esse motivo, geralmente é melhor usar a função
linspace que recebe como argumento o número de elementos que queremos, em vez da etapa:

In [167]:
#gerando 9 números igualmente espaçados entre 0 e 2
linspace = np.linspace(0, 2, 9)
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [170]:
from numpy import pi

#cria 100 valores igualmente espaçados entre 0 e 2pi
x = np.linspace(0, 2 * pi, 100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [171]:
#calculando o seno de todos os valores de x
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

**2.2.3 IMPRIMINDO MATRIZES**

Quando você imprime uma matriz, o NumPy a exibe de maneira semelhante às listas aninhadas, mas com o seguinte layout:

• o último eixo é impresso da esquerda para a direita,

• o penúltimo é impresso de cima para baixo,

• O restante também é impresso de cima para baixo, com cada fatia separada da próxima por uma linha vazia.

As matrizes unidimensionais são então impressas como linhas, as bidimensionais como matrizes e as tridimensionais como listas de matrizes.

In [172]:
#matriz 1d (linha)
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [173]:
#matriz 2d (matriz)
b = np.arange(12).reshape(4, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [174]:
#matriz 3d (listas de matrizes)
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

*Se uma matriz for muito grande para ser impressa, o
NumPy ignorará automaticamente a parte central da matriz e imprimirá apenas os cantos.

In [177]:
print(np.arange(10000))
print(np.arange(10000).reshape(100, 100))

[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


*Para desativar esse comportamento e forçar o NumPy a imprimir toda a matriz, você pode alterar as opções de
impressão usingset_printoptions.

In [178]:
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize) #o módulo sys deve ser importado

**2.2.4 OPERAÇÕES BÁSICAS**

*Operadores aritméticos em matrizes se aplicam elementarmente. Uma nova matriz é criada e preenchida com o resultado.

In [179]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [180]:
c = a - b
c

array([20, 29, 38, 47])

In [181]:
b**2

array([0, 1, 4, 9])

In [182]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [183]:
a < 35

array([ True,  True, False, False])

*Ao contrário de muitas linguagens de matriz, o operador do produto * opera elementar em matrizes NumPy. O
produto da matriz pode ser executado usando o operador @ (em python >=3.5) ou a função ou método de .dot:

In [184]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

A * B #produto elementar (multiplica elemento por elemento)

array([[2, 0],
       [0, 4]])

In [189]:
A @ B or A.dot(B) #produto matricial (multiplica linhas de A por colunas de B)

array([[5, 4],
       [3, 4]])

*Algumas operações, como += e *=, atuam no local para modificar uma matriz existente em vez de criar uma nova.

In [190]:
import numpy as np

rg = np.random.default_rng(1) #cria uma instância do número aleatório padrão gerador.
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [191]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [ ]:
a += b #b não é convertido automaticamente para o tipo inteiro (irá apresentar erro)

*Ao operar com matrizes de tipos diferentes, o tipo da matriz resultante corresponde ao mais geral ou preciso (um
comportamento conhecido como upcasting).

In [192]:
import math as mt
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, mt.pi, 3)
b.dtype.name

'float64'

In [196]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [197]:
c.dtype.name

'float64'

In [198]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [199]:
d.dtype.name

'complex128'

*Muitas operações unárias, como calcular a soma de todos os elementos na matriz, são implementadas como métodos
da classe ndarray

In [200]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [201]:
a.sum() #soma total.

np.float64(3.1057109529998157)

In [202]:
a.min() #mínimo.

np.float64(0.027559113243068367)

In [203]:
a.max() #máximo.

np.float64(0.8277025938204418)

*Por padrão, essas operações se aplicam à matriz como se fosse uma lista de números, independentemente de sua forma.
No entanto, especificando o parâmetro axis, você pode aplicar uma operação ao longo do eixo especificado de uma matriz:

In [204]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [205]:
b.sum(axis=0) #soma de cada coluna

array([12, 15, 18, 21])

In [206]:
b.min(axis=1) #valor mínimo de cada linha

array([0, 4, 8])

In [207]:
b.cumsum(axis=1) #soma acumulativa (linha por linha)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

**2.2.5 FUNÇÕES UNIVERSAIS**

*O NumPy fornece funções matemáticas familiares, como sin, cos e exp. No NumPy, elas são chamadas de "funções
universais" (ufunc). Dentro do NumPy, essas funções operam elementar em uma matriz, produzindo uma matriz como saída.

In [208]:
B = np.arange(3)
B

array([0, 1, 2])

In [209]:
#calcula a função exponencial p/ cada elemento de 'B'
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [210]:
#calculando a raiz quadrada de cada elemento de 'B'
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [212]:
C = np.array([2., -1., 4.])

#somando 'B' e 'C'
np.add(B, C)

array([2., 0., 6.])

**2.2.6 INDEXAÇÃO, FATIAMENTO E ITERAÇÃO**

*Matrizes unidimensionais podem ser indexadas, fatiadas e iteradas, assim como listas e outras sequências Python.

In [213]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [214]:
#terceiro elemento do array
a[2]

np.int64(8)

In [215]:
#slice do índice 2 até o 4 (o índice 5 não é incluído)
a[2:5]

array([ 8, 27, 64])

In [216]:
#atribuindo 100 aos índices 0, 2 e 4
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [218]:
#inversão
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [219]:
#calculando a raiz cúbica dos elementos de 'a'
for i in a:
  print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


*As matrizes multidimensionais podem ter um índice por eixo. Esses índices são dados em uma tupla separada por vírgulas:

In [220]:
def f(x, y):
  return 10 * x + y
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [221]:
#elemento presente na quarta coluna da terceira linha de 'b'
b[2, 3]

np.int64(23)

In [222]:
#cada linha na segunda coluna de 'b'
b[0:5, 1] or b[:, 1]

array([ 1, 11, 21, 31, 41])

In [223]:
#cada coluna na segunda e terceira linha de 'b'
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

*Quando menos índices são fornecidos do que o número de eixos, os índices ausentes são considerados fatias
completas:

In [46]:
#elementos presentes na última linha de 'b'
b[-1] or b[-1, :]

array([40, 41, 42, 43])

In [225]:
c = np.array([[[ 0, 1, 2], [ 10, 12, 13]],
              [[100, 101, 102], [110, 112, 113]]])

c.shape

(2, 2, 3)

In [226]:
#acessando o segundo bloco de 'c'
c[1, ...] or c[1, :, :] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [227]:
#acessando somente os últimos elementos das últimas colunas de cada linha
c[..., 2] or c[:, :, 2]

array([[  2,  13],
       [102, 113]])

*A iteração em matrizes multidimensionais é feita em relação ao primeiro eixo:

In [49]:
for row in b:
  print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


*No entanto, se alguém quiser realizar uma operação em cada elemento da matriz, pode-se usar o atributo flat que é
aniterator sobre todos os elementos da matriz:

In [50]:
for element in b.flat:
  print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


#2.3 MANIPULAÇÃO DE FORMAS

**2.3.1 MODIFICANDO A FORMA DE UMA MATRIZ**

*Uma matriz tem uma forma dada pelo número de elementos ao longo de cada eixo:

In [131]:
a = np.floor(10 * rg.random((3, 4)))
a

array([[4., 9., 9., 7.],
       [6., 8., 9., 0.],
       [1., 3., 0., 5.]])

In [132]:
a.shape

(3, 4)

*A forma de uma matriz pode ser alterada com vários comandos. Observe que os três comandos a seguir retornam um
array modificado, mas não alteram o array original:

In [133]:
#retorna o array achatado
a.ravel()

array([4., 9., 9., 7., 6., 8., 9., 0., 1., 3., 0., 5.])

In [134]:
#retorna o array com forma modificada
a.reshape(6, 2)

array([[4., 9.],
       [9., 7.],
       [6., 8.],
       [9., 0.],
       [1., 3.],
       [0., 5.]])

In [135]:
#retorna o array transposto
a.T

array([[4., 6., 1.],
       [9., 8., 3.],
       [9., 9., 0.],
       [7., 0., 5.]])

In [136]:
#dimensões de 'a'
a.shape

(3, 4)

In [137]:
#dimensões de 'a.T'
a.T.shape

(4, 3)

*A função reshape retorna seu argumento com uma forma modificada, enquanto o método
ndarray.resize modifica o próprio array:

In [138]:
a

array([[4., 9., 9., 7.],
       [6., 8., 9., 0.],
       [1., 3., 0., 5.]])

In [139]:
a.resize((2, 6))
a

array([[4., 9., 9., 7., 6., 8.],
       [9., 0., 1., 3., 0., 5.]])

*Se uma dimensão for dada como -1 em uma operação de remodelação, as outras dimensões serão calculadas automaticamente:

In [97]:
a.reshape(3, -1)

array([[1., 6., 3., 7.],
       [6., 4., 8., 6.],
       [8., 3., 5., 1.]])

**2.3.2 EMPILHANDO DIFERENTES MATRIZES**

*Várias matrizes podem ser empilhadas juntas ao longo de diferentes eixos:

In [111]:
#criando array 'a'
a = np.floor(10 * rg.random((2, 2)))
a

array([[8., 7.],
       [6., 2.]])

In [110]:
#criando array 'b'
b = np.floor(10 * rg.random((2, 2)))
b

array([[5., 3.],
       [7., 6.]])

In [113]:
#empilhando os arrays verticalmente
np.vstack((a, b))

array([[8., 7.],
       [6., 2.],
       [5., 3.],
       [7., 6.]])

In [115]:
#empilhando os arrays horizontalmente
np.hstack((a, b))

array([[8., 7., 5., 3.],
       [6., 2., 7., 6.]])

*A função column_stack empilha matrizes 1D como colunas em uma matriz 2D. É equivalente a hstack apenas para
matrizes 2D:

In [119]:
from numpy import newaxis
np.column_stack((a, b)) #com matriz 2D

array([[8., 7., 5., 3.],
       [6., 2., 7., 6.]])

In [120]:
a = np.array([4., 2.])
b = np.array([3., 8.])
np.column_stack((a, b)) #retorna uma matriz 2D

array([[4., 3.],
       [2., 8.]])

In [121]:
np.hstack((a, b)) #o resultado é diferente

array([4., 2., 3., 8.])

In [123]:
a[:, newaxis] #veja 'a' como um vetor de coluna 2D

array([[4.],
       [2.]])

In [124]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [125]:
np.hstack((a[:, newaxis], b[:, newaxis])) #o resultado é o mesmo

array([[4., 3.],
       [2., 8.]])

***2.3.3 DIVIDINDO UM ARRAY EM VÁRIOS MENORES***

*Usando hsplit, você pode dividir uma matriz ao longo de seu eixo horizontal, especificando o número de matrizes de
formato igual para retornar ou especificando as colunas após as quais a divisão deve ocorrer:

In [126]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[7., 2., 0., 9., 5., 7., 5., 6., 0., 1., 6., 5.],
       [1., 9., 1., 5., 1., 7., 2., 1., 0., 1., 1., 5.]])

In [129]:
#dividindo 'a' em 3
np.hsplit(a, 3)

[array([[7., 2., 0., 9.],
        [1., 9., 1., 5.]]),
 array([[5., 7., 5., 6.],
        [1., 7., 2., 1.]]),
 array([[0., 1., 6., 5.],
        [0., 1., 1., 5.]])]

In [130]:
#dividindo 'a' após a terceira e a quarta coluna
np.hsplit(a, (3, 4))

[array([[7., 2., 0.],
        [1., 9., 1.]]),
 array([[9.],
        [5.]]),
 array([[5., 7., 5., 6., 0., 1., 6., 5.],
        [1., 7., 2., 1., 0., 1., 1., 5.]])]