<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/Emanuel_Oliveira/atv_de_casa_da_aula_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Página 6:

In [ ]:
import numpy as np
a = np.arange(15).reshape(3, 5)
np.array([[ 0, 1, 2, 3, 4],
      [ 5, 6, 7, 8, 9],
      [10, 11, 12, 13, 14]])
type(a)

numpy.ndarray

In [ ]:
a.shape


(3, 5)

In [ ]:
a.ndim


2

In [ ]:
a.dtype.name


'int64'

In [ ]:
a.itemsize


8

In [ ]:
a.size


15

In [ ]:
b = np.array([6, 7, 8])
np.array([6, 7, 8])
type(b)

numpy.ndarray

Página 7:

In [2]:
import numpy as np
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [3]:
a.dtype

dtype('int64')

In [4]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [8]:
a = np.array(1, 2, 3, 4)
a

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [9]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [10]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [12]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [14]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Página 8:

In [15]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [16]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [17]:
from numpy import pi
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [20]:
x = np.linspace(0, 2 * pi, 100)

In [21]:
 f = np.sin(x)

In [22]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [23]:
b = np.arange(12).reshape(4, 3) # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [24]:
c = np.arange(24).reshape(2, 3, 4) # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [25]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [26]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [ ]:
np.set_printoptions(threshold = sys.maxsize)

Página 9:

In [33]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [34]:
c = a - b
c

array([20, 29, 38, 47])

In [35]:
b**2

array([0, 1, 4, 9])

In [36]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [37]:
a < 35

array([ True,  True, False, False])

In [38]:
A = np.array([[1, 1],
               [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B

array([[2, 0],
       [0, 4]])

In [39]:
A @ B

array([[5, 4],
       [3, 4]])

In [40]:
A.dot(B)

array([[5, 4],
       [3, 4]])

Página 10:

In [41]:
rg = np.random.default_rng(1)

In [42]:
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [43]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [44]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [45]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [46]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [47]:
c.dtype.name

'float64'

In [48]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [49]:
d.dtype.name

'complex128'

In [50]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [51]:
a.sum()

np.float64(3.1057109529998157)

In [52]:
a.min()

np.float64(0.027559113243068367)

In [53]:
a.max()

np.float64(0.8277025938204418)