<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/gabriel_coelho/aula7.1%20%2B%20atividade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY 1.0

In [2]:
#CRIAÇÃO DA LISTA HEIGHT
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [11]:
#CRIAÇÃO DA LISTA WEIGHT
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [7]:
#A OPERAÇÃO DEVE APRESENTAR UM ERRO
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [8]:
import numpy as np
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [13]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [14]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

*OPERADOR SOMA EM ARRAY E LISTA*

In [18]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [19]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [20]:
numpy_array + numpy_array

array([2, 4, 6])

*ANALISANDO ARRAYS*

In [21]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [22]:
bmi[1]

np.float64(20.97505668934241)

In [23]:
bmi > 23

array([False, False, False,  True, False])

In [24]:
bmi[bmi > 23]

array([24.7473475])

*NUMPY 2.0*

In [49]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], #A VÍRGULA ENTRE OS COLCHETES DEFINE AS LINHAS DO ARRAY
                  [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [50]:
np_2d.shape

(2, 5)

In [51]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
          [65.4, 59.2, 63.6, 88.4, '68.7']])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

*ACESSANDO ELEMENTOS DE UM ARRAY*

In [52]:
            #0    #1    #2    #3    #4
np.array([[1.73, 1.68, 1.71, 1.89, 1.79], #0
          [65.4, 59.2, 63.6, 88.4, 68.7]]) #0

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [53]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [54]:
np_2d[0][2] or np_2d[0, 2]

np.float64(1.71)

In [55]:
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [56]:
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

#ATIVIDADE DE CLASSE

1) Importe a biblioteca numpy com acesso via np na linha 6.

2) Use np.array() para converter a lista baseball para um array chamado np_baseball.

3) Print o tipo da estrutura de dados np_baseball.

4) Print as dimensões do array np_baseball.


In [81]:
#CREATE LIST BASEBALL
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

#IMPORT THE NUMPY PACKAGE AS NP
import numpy as np

#CREATE A NUMPY ARRAY FROM BASEBALL: NP_BASEBALL
np_baseball = np.array(baseball)
print(np_baseball)

#PRINT OUT TYPE OF NP_BASEBALL
print(type(np_baseball))

#1
np_2d = np_baseball
np_2d

#2
np_2d.shape

[180 215 210 210 188 176 209 200]
<class 'numpy.ndarray'>


(8,)