<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/kauan_lima/aula_04_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pratique

In [2]:
#1
True==False

False

In [4]:
#2
-5 * 15 == 75

False

In [5]:
#3
"pyscript"=="pyScript"

False

In [6]:
#4
True==1

True

Pratique

In [10]:
#1
import numpy as np
my_house=np.array([18.0,20.0,10.75,9.50])
your_house=np.array([14.0,24.0,14.25,9.0])
my_house[my_house>18]

array([20.])

In [30]:
#2
my_house[my_house > your_house]

array([18. ,  9.5])

In [13]:
y=5
y > 5 or y > 13

False

In [14]:
import numpy as np
np_height=np.array([1.73,1.68,1.71,1.89,1.79])
np_weight=np.array([65.4,59.2,63.6,88.4,68.7])
bmi=np_weight/np_height**2
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [15]:
bmi > 30

array([False, False, False, False, False])

In [20]:
bmi[bmi < 23]

array([21.85171573, 20.97505669, 21.75028214, 21.44127836])

In [18]:
np.logical_and(bmi > 21,bmi < 22)

array([ True, False,  True, False,  True])

In [19]:
bmi[np.logical_and(bmi >21, bmi < 22)]

array([21.85171573, 21.75028214, 21.44127836])

Pratique

In [23]:
my_kitchen=18.0
your_kitchen=14.0

In [22]:
#1
my_kitchen > 10 and my_kitchen < 18

False

In [24]:
#2
my_kitchen < 14 and my_kitchen < 17

False

In [25]:
#3
my_kitchen*2 < your_kitchen*3

True

In [27]:
#4
my_house.all() > 18.5 or my_house.all() < 10
print(my_house[my_house > 18.5])
print(my_house[my_house < 10])

[20.]
[9.5]


In [28]:
#5
np.logical_and(my_house < 11, your_house < 11)

array([False, False, False,  True])

Operadores condicionais

In [31]:
z = 5
if z % 2 == 0:
  print("z is even")
else:
  print("z is odd")

z is odd


In [32]:
x=3
if x % 2 == 0:
  print("x é divisível por 2")
elif x % 3 == 0:
  print("x é divisível por 3")
else:
  print("x não é divisível por 2 nem por 3")

x é divisível por 3


Questões

In [34]:
#1
room= 'kit'
area = 14.0

In [35]:
if room == "kit":
  print("Looking around in the kitchen.")

Looking around in the kitchen.


In [36]:
if area > 15:
  print("Big Place")
else:
  print("Pretty Small")

Pretty Small
