<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/Thiago_Gomes/Aula07_e_Aula08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exemplos de bibliotecas

In [7]:
#EX: 01
import numpy
array ([1,2,3])

NameError: name 'array' is not defined

In [8]:
#EX: 02
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [9]:
#EX: 03
numpy.array([1,2,3])

array([1, 2, 3])

In [10]:
#EX: 04
from numpy import array
array([1,2,3])

array([1, 2, 3])

Atividade de bibliotecas aula07

In [11]:
r = 0.43
c = 0
a = 0

#1) na linha 5 importe a biblioteca math
import math

#2) calcule o comprimento de uma circunferencia e armazene o resultado em c obs c = 2*math.pi*r
c = 2*math.pi*r

#3) calcule o resultado da circunferencia e armazene em a
a = math.pi*r**2

print(c)
print(a)


2.701769682087222
0.5808804816487527


Exemplos de bibliotecas aula 08

In [28]:
#EX: 01
height = [1.73, 1.68, 1.71, 1.79, 1.90]
print(height)

weight = [65.4, 59.2, 63.6, 88.4, 68.7]
print(weight)

print (weight / height ** 2)


[1.73, 1.68, 1.71, 1.79, 1.9]
[65.4, 59.2, 63.6, 88.4, 68.7]


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [29]:
#EX: 02
import numpy as np
np_height = np.array(height)
print (np_height)

np_weight = np.array(weight)
print (np_weight)
np_weight + np.array(weight)

bmi = np_weight / np_height ** 2
print (bmi)


[1.73 1.68 1.71 1.79 1.9 ]
[65.4 59.2 63.6 88.4 68.7]
[21.85171573 20.97505669 21.75028214 27.58965076 19.03047091]


In [32]:
#EX: 03
python_list = [1,2,3]
numpy_array = np.array([1,2,3])

print (python_list + python_list)


[1, 2, 3, 1, 2, 3]


In [30]:
#EX: 04
print (bmi)
print (bmi[1])
print (bmi > 23)
print (bmi[bmi > 23])

[21.85171573 20.97505669 21.75028214 27.58965076 19.03047091]
20.97505668934241
[False False False  True False]
[27.58965076]


In [34]:
#EX: 05
np_2d = np.array([[1.73, 1.71, 1.79, 1.9], [65.4, 59.2, 63.6, 88.4, 68.7,]])
print (np_2d)
print (np_2d.shape)

#so é possivel ter arrays caso as listas que o compoem tenham o mesmo numero de elementos caso contrário dará erro

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [40]:
#EX: 06
np_2d = np.array([[1.73, 1.71, 1.79, 1.9, 1.77], [65.4, 59.2, 63.6, 88.4, 68.7,]])
print (np_2d)
print (np_2d.shape)

np_2d[1]



[[ 1.73  1.71  1.79  1.9   1.77]
 [65.4  59.2  63.6  88.4  68.7 ]]
(2, 5)


array([65.4, 59.2, 63.6, 88.4, 68.7])

In [43]:
np_2d[1][2]
np_2d[1,2:]
np_2d[:, 1:3]

array([[ 1.71,  1.79],
       [59.2 , 63.6 ]])

Atividade de bibliotecas aula 08

In [48]:
import numpy as np
#1) importe a biblioteca numpy com o ascesso via np na linha 6
baseball = [180, 215, 210, 210, 188, 176, 200]

#2) use o np.array() para convertr a lista baseball para um array camado np_baseball
np_baseball = np.array(baseball)
print (np_baseball)

#3) print o tipo da estrutura de dados np_baseball
type(np_baseball)

#4) printe as dimensões do array np_baseball
print(np_baseball.shape)

[180 215 210 210 188 176 200]
(7,)
