<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/antonio_erick/aula6_Pag_69_81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random as rd
import numpy as np
#height= autura
#whight= peso
#geração de numeros entre 150 e 209
height = range(150,210)

#geração de numeros entre 50 e 149
weight = range(50,149)

#amostra randomica de 20 numeros de height
height=rd.sample(height,20)

#amostra randomica de 20 numeros de weight
weight = rd.sample(weight,20)

#converter height em array e normalizar multiplicando por 0.01
height_array = np.array(height)*0.01
print(height_array)
#converter weight em array
weight_array=np.array(weight)
print(weight_array)

 #calculo do BMI
bmi = weight_array/(height_array**2)

#verificação onde BMI é menor que 21
light =bmi<21
# print light
print(light)

#exibição dos valores de bmi com valor menor que 21
print(f'{bmi[bmi<21]}')

#Print o elementos de weight_array do index 8 até o index 15,
#incluindo o index 15
#slice wheight_array [8:15]
print(f'{weight_array[8:16]}')

#Print os elementos height_arra do index 11 até o index 19,
#incluindo o index 19
print(f'{height_array[11:20]}')

[2.07 1.68 2.   2.01 1.51 1.96 1.76 2.06 2.09 1.97 1.65 1.5  1.62 1.83
 1.6  1.52 1.84 1.59 1.75 1.79]
[131  83 126  95  72 137  87 100 102  54  55  84  53 112 105  69 125 103
  59  79]
[False False False False False False False False False  True  True False
  True False False False False False  True False]
[13.91429823 20.2020202  20.19509221 19.26530612]
[102  54  55  84  53 112 105  69]


In [ ]:
import random as rd
import numpy as np
city1=[5,10]
city2=[8,20]
city3=[4,15]
np_city = np.array([city1,city2,city3])
print(np_city)
#mean média
print(np.mean(np_city[:,0]))
#média inteira
print(np.median(np_city[:,0]))

[[ 5 10]
 [ 8 20]
 [ 4 15]]
5.666666666666667
5.0
[[1.         0.72057669]
 [0.72057669 1.        ]]
1.699673171197595


In [ ]:
print(np.corrcoef(np_city[:,0],np_city[:,1]))
print(np.std(np_city[:,0]))

[[1.         0.72057669]
 [0.72057669 1.        ]]
1.699673171197595


In [ ]:
height1= np.round(np.random.normal(1.75,0.20,5000),2)
print(height1)
weight1=np.round(np.random.normal(60.32,15,5000),2)
print(weight1)
np_city2= np.column_stack((height1,weight1))
print(np_city2)

[1.91 1.8  1.13 ... 1.89 1.91 1.74]
[60.7  55.03 44.83 ... 57.13 63.59 57.62]
[[ 1.91 60.7 ]
 [ 1.8  55.03]
 [ 1.13 44.83]
 ...
 [ 1.89 57.13]
 [ 1.91 63.59]
 [ 1.74 57.62]]


Pratique pag 72

In [64]:
import numpy as  np
baseball=[[180, 78.4],
          [215, 102.7],
          [210, 98.5],
          [188,75.2]]
np_baseball = np.array(baseball)
#1 Print a terceira linha de np_baseball na linha 14 do código.
print(np_baseball[2])
#2 Crie uma nova variável np_weight_lb que recebe toda a segunda coluna de np_baseball.
np_weight_lb=np_baseball[:,1]
print(np_weight_lb)
#3 Print a primeira coluna da segunda linha de Np_baseball na linha  do código.
print(np_baseball[1:2,0])
#4 Calcule e exiba a média da primeira coluna de np_baseball.
print(np.mean(np_baseball[:,0]))
#5 Calcule e exiba a mediana da segunda linha de np_baseball.
print(np.median(np_baseball[1:2]))


[210.   98.5]
[ 78.4 102.7  98.5  75.2]
[215.]
198.25
158.85


Exercício pag 73 até 81


In [ ]:
#1 Qual linha de comando exibe a documentação da função len()
help(len)

In [68]:
#2 Qual dos 3 códigos printa o número 8?
import numpy as np
z=np.array([[9,9,3],
            [8,5,4]])
print(z[1,0])

8


In [69]:
#3
foo=[0.2, 1.7, 'a', 'wed', '1.5']
print(foo)
foo[0:2]= [2.75, -1.5]
print(foo)

[0.2, 1.7, 'a', 'wed', '1.5']
[2.75, -1.5, 'a', 'wed', '1.5']


In [71]:
4# print('datascience'.replace('science','camp'))

datacamp


In [74]:
#5) Qual linha de código apresenta erro ?
print('Python' * int('2'))
print('Python' * 2)
#print('Python' * '2')
print('Python * 2')

PythonPython
PythonPython
Python * 2


In [76]:
#6) Qual código retorna o texto: python data
x= 'python'
print(x + ' data')#esse
x= 'r'
print(x + ' data')
x= 'sql'
print(x + ' data')

python data
r data
sql data


In [77]:
#7) Considerando esse código
np_2d=np.array([[1.5, 6.4, 7.8, 2.2],
                [4.3, 8.7, 1.9, 3.4],
                [5.3, 7.3, 9.4, 2.5]])
#:Qual opção ao lado representa o comando:
print(np_2d[2:,2:])
#[[9.4 2.5]]

[[9.4 2.5]]


In [81]:
#8) Complete o código para a saída 6666
print('6' * (2**2))

6666


In [82]:
#9) Qual a saída do código ao lado ?
import numpy as np
m= np.array ([2,6,4])
n= np.array ([2,1,1])
print(m*n)
#[4 6 4]

[4 6 4]
