<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/gabriel_coelho/aula7.2%20%2B%20atividade%20-%20LdP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PRATIQUE p. 68

In [ ]:
import random as rd
import numpy as np

#GERAÇÃO DE NÚMEROS ENTRE 150 E 209
height = range(150, 210)

#GERAÇÃO DE NÚMEROS ENTRE 50 E 149
weight = range(50, 150)

#AMOSTRA RANDOMICA DE 20 NÚMEROS DE HEIGHT
height = rd.sample(height, 20)

#AMOSTRA RANDOMICA DE 20 NÚMEROS DE WEIGHT
weight = rd.sample(weight, 20)

#CONVERTER HEIGHT EM ARRAY E NORMALIZAR MULTIPLICANDO POR 0.01
height_array = np.array(height)*0.01
print(height_array)

#CONVERTER WEIGHT EM ARRAY
weight_array = np.array(weight)
print(weight_array)

#CÁLCULO DO BMI
bmi = weight_array/height_array**2

#VERIFICAÇÃO ONDE BMI É MENOR QUE 21
light = bmi < 21

#PRINT LIGHT
print(light)

#EXIBIÇÃO DOS VALORES DE BMI COM VALOR MENOR QUE 21
print(bmi[bmi < 21])

#PRINT O ELEMENTO DE WEIGHT_ARRAY DO INDEX 8 ATÉ O INDEX 15, INCLUINDO O INDEX 15
print(weight_array[8:16])

#PRINT O ELEMENTO HEIGHT_ARRAY DO INDEX 11 ATÉ O INDEX 19, INCLUINDO O INDEX 19
print(height_array[11:20])

[1.71 1.57 1.6  1.64 2.03 2.04 2.02 1.92 1.63 1.74 1.56 1.79 1.77 1.89
 1.82 1.98 1.51 2.07 1.99 2.06]
[114  64 138 115 124  92 141 118  68  55  61 108  70 145  82 131  86  77
 139 135]
[False False False False False False False False False  True False False
 False False False False False  True False False]
[18.16620425 17.97008098]
[ 68  55  61 108  70 145  82 131]
[1.79 1.77 1.89 1.82 1.98 1.51 2.07 1.99 2.06]


#NUMPY

In [ ]:
import random as rd
import numpy as np

city1 = [5,10]
city2 = [8,20]
city3 = [4,15]
np_city = np.array([city1, city2, city3])

In [ ]:
np.mean(np_city[:, 0])

np.float64(1.745756)

In [ ]:
np.median(np_city[:, 0])

np.float64(5.0)

In [ ]:
np.corrcoef(np_city[:, 0], np_city[:, 1])

array([[1.        , 0.72057669],
       [0.72057669, 1.        ]])

In [ ]:
np.std(np_city[:, 0])

np.float64(1.699673171197595)

#GERAÇÃO DE UM ARRAY RANDÔMICO

In [ ]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))
print(np_city)

[[ 1.79 75.51]
 [ 1.66 55.59]
 [ 1.41 65.03]
 ...
 [ 2.26 83.71]
 [ 1.52 63.82]
 [ 1.9  78.73]]


#PRATIQUE p. 72

1) Print a terceira linha de np_baseball na linha 14 do código.

2) Crie uma nova variável np_weight_lb que recebe toda a segunda coluna de np_baseball.

3) Print a primeira coluna da segunda linha de Np_baseball na linha  do código.

4) Calcule e exiba a média da primeira coluna de np_baseball.

5) Calcule e exiba a mediana da segunda linha de np_baseball.

In [ ]:
#CREATE BASEBALL, A LIST OF LISTS
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

#IMPORT NUMPY PACKAGE
import numpy as np

#CREATE NP_BASEBALL (2COLS)
np_baseball = np.array(baseball)

#1
print(np_baseball[2])

#2
np_weight_lb = np_baseball[:, 1]
print(np_weight_lb)

#3
print(np_baseball[1, 0])

#4
print(np.mean(np_baseball[:, 0]))

#5
print(np.median(np_baseball[1]))

[210.   98.5]
[ 78.4 102.7  98.5  75.2]
215.0
198.25
158.85


#EXERCÍCIO

1) Qual linha de comando exibe a documentação da função len()

In [ ]:
a - help(len) #correto. help(função) exibe o que a função faz.
b - doc(len) #incorreto. não existe em python.
c - doc(len()) #incorreto. não é possível rodar len() sem nenhum valor.
d - find(len) #incorreto. não é uma função padrão.

2) Qual dos 3 códigos printa o número 8?

In [ ]:
import numpy as np
z = np.array([[9, 9, 2],
              [8, 5, 4]])
print(z[1, 0]) #correto. primeiro se acessa a linha, depois a coluna.

import numpy as np
z = np.array([[9, 9, 2],
              [8, 5, 4]])
print(z[0, 2]) #incorreto. irá retornar o número 2.

import numpy as np
z = np.array([[9, 9, 2],
              [8, 5, 4]])
print(z[0, 1]) #incorreto. irá retornar o número 9.

In [1]:
#3 - substituição por fatiamento.
foo = [0.2, 1.7, 'a', 'wed', '1.5']
foo[0:2] = [2.75, -1.5]
print(foo)

[2.75, -1.5, 'a', 'wed', '1.5']


In [3]:
#4 - a função REPLACE é usada para substituir uma string por outra.
'datascience'.replace('science', 'camp')

'datacamp'

5) Qual linha de código apresenta erro?

In [ ]:
a - 'Python' * int('2') #correto. reetirá a string 2 vezes.
b - 'Python' * 2 #correto. multiplicação da string por um número inteiro.
c - 'Python' * '2' #incorreto. não é possível multiplicar uma string por outra.
d - 'Python * 2' #correto. não é uma operação, mas uma frase. não há erro.

6) Qual código retorna o texto:
 python data?

In [ ]:
a - x = 'python'
print(x + ' data') #correto. retorna 'python data'.

b - x = 'r'
print(x + ' data') #incorreto. retorna 'r data'.

c - x = 'sql'
print(x + ' data') #incorreto. retorna 'sql data'.

7) Considerando esse código:

In [ ]:
np_2d = np.array([[1.5, 6.4, 7.8, 2.2],
                  [4.3, 8.7, 1.9, 3.4],
                  [5.3, 7.3, 9.4, 2.5]])

Qual opção abaixo representa o comando:

In [ ]:
np_2d[2:, 2:]

In [ ]:
a - 5.3 #incorreto.
b - 4.3 #incorreto.
c - array([[9.4, 2.5]]) #correto.

8) Complete o código para a saída 6666

In [4]:
print('6' * (2 ** 2))

6666


9) Qual a saída do código abaixo?

In [7]:
import numpy as np
m = np.array([2, 6, 4])
n = np.array([2, 1, 1])
print(m * n)

[4 6 4]
