<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/david_lucasgs/Aula_05_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import random as rd

In [56]:
import numpy as np

In [82]:
height = list(range(150, 210))
height

[150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209]

In [83]:
weight = list(range(50, 149))
weight

[50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148]

In [84]:
height = rd.sample(height, 20)
height

[209,
 195,
 158,
 173,
 179,
 207,
 206,
 169,
 196,
 205,
 180,
 176,
 160,
 155,
 202,
 194,
 193,
 153,
 183,
 166]

In [85]:
weight = rd.sample(weight, 20)
weight

[130,
 91,
 141,
 83,
 123,
 125,
 96,
 67,
 142,
 124,
 64,
 140,
 112,
 50,
 133,
 73,
 102,
 89,
 120,
 72]

In [94]:
height_array = np.array(height)*0.01
height_array

array([2.09, 1.95, 1.58, 1.73, 1.79, 2.07, 2.06, 1.69, 1.96, 2.05, 1.8 ,
       1.76, 1.6 , 1.55, 2.02, 1.94, 1.93, 1.53, 1.83, 1.66])

In [98]:
weight_array = np.array(weight)
weight_array

array([130,  91, 141,  83, 123, 125,  96,  67, 142, 124,  64, 140, 112,
        50, 133,  73, 102,  89, 120,  72])

In [99]:
bmi = weight_array/(height_array**2)
bmi

array([29.76122342, 23.93162393, 56.48133312, 27.73229978, 38.38831497,
       29.17220939, 22.62230182, 23.45856238, 36.9637651 , 29.50624628,
       19.75308642, 45.19628099, 43.75      , 20.81165453, 32.59484364,
       19.39632267, 27.38328546, 38.01956512, 35.83266147, 26.12861083])

In [100]:
light = bmi < 21

In [101]:
light

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False,  True, False, False,
       False, False])

In [102]:
bmi[light]

array([19.75308642, 20.81165453, 19.39632267])

In [104]:
weight_array [8:16]

array([142, 124,  64, 140, 112,  50, 133,  73])

In [105]:
height_array [11:20]

array([1.76, 1.6 , 1.55, 2.02, 1.94, 1.93, 1.53, 1.83, 1.66])