<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/yana_karen/Aula3005.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as mp

In [5]:
pip install numpy==2.0.1

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 86.9 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2


In [6]:
pip install numpy==2.0.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 52.1 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.1
    Uninstalling numpy-2.0.1:
      Successfully uninstalled numpy-2.0.1


In [7]:
pip install pydicom

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 18.6 MB/s eta 0:00:00


In [10]:
import numpy
array([1, 2, 3])

NameError: name 'array' is not defined

In [11]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [12]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [13]:
from numpy import array
array([1, 2, 3])

array([1, 2, 3])

In [14]:
import numpy as np

fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]


fam_ext = fam + ["me", 1.79]


print(str(len(fam_ext)) + " elements in fam_ext")


np_fam = np.array(fam_ext)

10 elements in fam_ext


Questão 1

In [15]:
r = 0.43

In [16]:
import math

Questão 2

In [17]:
C = 0
C = 2*math.pi*r
C

2.701769682087222

Questão 3

In [18]:
A = 0
A = math.pi*r**2
A

0.5808804816487527

In [19]:
print("Circunferência: " + str(C))
print("Área: " + str(A))

Circunferência: 2.701769682087222
Área: 0.5808804816487527


Aula da tarde

In [20]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [21]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [22]:
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [23]:
import numpy as np
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [24]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [25]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [26]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [27]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [28]:
numpy_array + numpy_array

array([2, 4, 6])

In [29]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [30]:
bmi[1]

np.float64(20.97505668934241)

In [31]:
bmi > 23

array([False, False, False,  True, False])

In [32]:
bmi[bmi > 23]

array([24.7473475])

In [33]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [34]:
np_2d.shape

(2, 5)

In [35]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
          [65.4, 59.2, 63.6, 88.4, "68.7"]])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

1 - a

In [36]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])
np.delete(np_2d, 1, axis=0)

array([[1.73, 1.68, 1.71, 1.89, 1.79]])

1 - b

In [38]:
np_3d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])
nova_linha = [1.7, 4.8, 2.0, 7.5, 9.4]
np_3d = np.append(np_3d, [nova_linha], axis=0)
np_3d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ],
       [ 1.7 ,  4.8 ,  2.  ,  7.5 ,  9.4 ]])

In [39]:
np_3d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])
nova_linha = [1.7, 2.0, 7.5, 9.4]
np_3d = np.append(np_3d, [nova_linha], axis=0)
np_3d

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 4

Não é possível ter uma lista com diferentes números de colunas, pois, para concatenar, o número de colunas precisa ser o mesmo.

In [40]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [41]:
np_2d[0][2]

np.float64(1.71)

In [42]:
np_2d[0, 2]

np.float64(1.71)

In [43]:
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [44]:
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

Questão 1

In [45]:
import numpy as np

Questão 2

In [48]:
baseball = [180, 215, 210, 210,
            188, 176, 209, 200]
np_baseball = np.array(baseball)
np_baseball

array([180, 215, 210, 210, 188, 176, 209, 200])

Questão 3

In [49]:
type(np_baseball)

numpy.ndarray

Questão 4

In [50]:
np_baseball.shape

(8,)