<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/joao_pedro/Aula_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [ ]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [ ]:
weight/height**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
import numpy as np


In [ ]:
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [ ]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [ ]:
imc = np_weight/np_height**2
imc

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [ ]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [ ]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [ ]:
numpy_array + numpy_array

array([2, 4, 6])

In [ ]:
imc

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [ ]:
imc[1]

np.float64(20.97505668934241)

In [ ]:
imc > 23

array([False, False, False,  True, False])

In [ ]:
imc[imc > 23]

array([24.7473475])

In [ ]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [ ]:
np_2d.shape

(2, 5)

In [ ]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])