<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/Kemilly_Mota/aula7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  #operadores de comparação
import numpy as np
np_altura =  np.array([1.73,1.68,1.71,1.89,1.79])
np_peso = np.array ([65.4,59.3,63.6,88.4,68.7])
bmi = np_peso / np_altura **2
bmi

array([21.85171573, 21.01048753, 21.75028214, 24.7473475 , 21.44127836])

In [ ]:
#Para 1 valor de peso e um valor de altura, print na tela: Você está com sobrepeso se bmi > 30, caso contrário, você esta com peso adequado. 139

In [ ]:
print(bmi<23)

[ True  True  True False  True]


In [ ]:
#slide 143
#verifique a igualdade entre duas variáveis booleanas. Nesse caso, True e False.
False == "False"
True == "True"
print(False == True)

False


In [ ]:
#Verifique se a multiplicação -5 * 15 é igual a 75
multiplicacao = (-5*15)
multiplicacao == 75

False

In [ ]:
#Verifique se as strings "pyscript" e  "PyScript"  são iguais.
"pyscript" == "PyScript"

False

In [ ]:
#Verfiue se a variaável booleana True é igual a 1.
True == 1

True

In [ ]:
import numpy as np
my_house = np.array([18.0,20.0,10.75,9.50])
your_house = np.array ([14.0,24.0,14.25,9.0])

print(bmi > 18)

print(my_house < your_house)

[ True  True  True  True  True]
[False  True  True False]


In [ ]:
x = 12
x < 5 and x > 15

False

In [ ]:
y = 5
y > 7 or y < 2

False

In [ ]:
np.logical_and (bmi > 21, bmi < 22)

array([ True,  True,  True, False,  True])

In [ ]:
bmi[np.logical_and( bmi > 21, bmi < 22)]

array([21.85171573, 21.01048753, 21.75028214, 21.44127836])

In [ ]:
my_kitchen = 18.0
your_kitchen = 14.0

my_kitchen > 10 and my_kitchen < 18

True

In [ ]:
my_kitchen < 14 or my_kitchen < 17

False

In [ ]:
my_kitchen * 2 < my_kitchen * 3

True

In [ ]:
import numpy as np
my_house[np.logical_or(my_house > 18.5, my_house < 10)]

array([20. ,  9.5])

In [ ]:
print(my_house < 11)
print(your_house < 11)
np.logical_and(my_house < 11 , your_house < 11)

[False False  True  True]
[False False False  True]


array([False, False, False,  True])

In [ ]:
z = 5
if z % 2 == 0:
  print(f"{z} é um número par")
else :
  print(f"{z} é ímpar")

5 é ímpar


In [ ]:
z = 10
if z % 2 == 0:
  print(f"{z} é um número par")
else :
  print(f"{z} é ímpar")

10 é um número par


In [ ]:
z = 6
if z % 2 == 0:
  print(f"{z} é divisivel por 2")
elif z % 3 == 0:
  print(f"{z} é divisivel por 3")
else:
  print(f"{Z} não é dividido por 3 nem por 2")

6 é divisivel por 2


In [ ]:
room = 'kit'
area = 14.0
if area > 15:
  print("Big place")
else :
  print("Pretty small")

Pretty small
