<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/gabriel_coelho/aula11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#OPERADORES DE COMPARAÇÃO

In [1]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [2]:
bmi > 23 #parâmetro para todos.

array([False, False, False,  True, False])

In [3]:
bmi[bmi > 23] #parâmetro para um específico.

array([24.7473475])

Exercício:

1) Para 1 valor de peso e um valor de altura, print na tela: Você está com sobrepeso se bmi > 30, caso contrário, você esta com peso adequado.

2) Para o Array resposta do exemplo ao lado print, usando operador lógico, onde bmi é menor que 23.


In [9]:
import numpy as np
np_height = np.array([1.60])
np_weight = np.array([75])
bmi = np_weight / np_height ** 2
bmi

array([29.296875])

In [10]:
#1
if bmi > 30:
  print('Você está com sobrepeso.')
else:
  print('Você está com peso adequado.')

Você está com peso adequado.


In [12]:
#2
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
bmi[bmi < 23]

array([21.85171573, 20.97505669, 21.75028214, 21.44127836])

#TIPOS DE OPERADORES DE COMPRARAÇÃO

1) > : maior que

2) < : menor que

3) >= : maior ou igual a

4) <= : menor ou igual a

5) == : igual a

6) != : diferente de

7) is : é

8) is not : não é

* OBS: Não se pode comparar inteiro com string.

#PRATIQUE

1) Verifique a igualdade entre duas variáveis booleanas. Nesse caso, True e False.

2) Verifique se a multiplicação -5 * 15 é igual a 75.

3) Verifique se as strings "pyscript" e  "PyScript"  são iguais.

4) Verfique se a variável booleana True é igual a 1.


In [16]:
#COMPARISON OF BOOLEANS
A = True == False
print(A)

#COMPARISON OF INTEGERS
B = -5 * 15 == 75
print(B)

#COMPARISON OF STRINGS
C = 'pyscript' == 'PyScript'
print(C)

#COMPARE A BOOLEAN WITH AN INTEGER
D = True == 1
print(D)

False
False
False
True


1) Print  a verificação de quais elementos são maiores que 18 no array my_house.

2) Print  a verificação de quais elementos em my_house são menores que no arrray your_house.

In [23]:
#CREATE ARRAYS
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

#my_house GREATER THAN OR EQUAL TO 18
maiores = my_house > 18
print(maiores)

#my_house LESS THAN your_house
menores = my_house < your_house
print(menores)

[False  True False False]
[False  True  True False]


#TIPOS DE OPERADORES BOOLEANOS

and

or

not

#OPERADORES BOOLEANOS COM NUMPY

logical_and()

logical_or()

logical_not()

In [24]:
np.logical_and(bmi > 21, bmi < 22) #retorna a verificação.

array([ True, False,  True, False,  True])

In [31]:
bmi[np.logical_and(bmi > 21, bmi < 22)] #retorna os elementos.

array([21.85171573, 21.75028214, 21.44127836])

#PRATIQUE

1) Verifique se my_kitchen é maior que 10 e menor que 18.

2) Verifique se my_kitchen é menor que 14 e menor que 17.

3) Verifique se o dobro de my_kitchen é menor que o triplo de your_kitchen.

In [32]:
#DEFINE VARIABLES
my_kitchen = 18.0
your_kitchen = 14.0

#my_kitchen BIGGER THAN 18 AND SMALLER THAN 18?
vf1 = my_kitchen > 10 and my_kitchen < 18
print(vf1)

#my_kitchen SMALLER THAN 14 OR BIGGER THAN 17?
vf2 = my_kitchen < 14 and my_kitchen < 17
print(vf1)

#DOUBLE my_kitchen SMALLER THAN TRIPLE your_kitchen?
vf3 = 2 * my_kitchen < 3 * your_kitchen
print(vf3)

False
False
True


1) Verifique quais elementos de my_house são maiores que 18.5 ou menores que 10.

2) Verifique quais elementos das mesmas posições dos arrays possuem valor menor que 11.

In [39]:
#CREATE ARRAYS
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

#my_house GREATER THAN 18.5 OR SMALLER THAN 10
vf4 = np.logical_or(my_house > 18.5, my_house < 10)
print(vf4)

#BOTH my_house AND your_house SMALLER THAN 11
menor11 = np.logical_and(my_house < 11, your_house < 11)
print(menor11)

[False  True False  True]
[False False False  True]


#OPERADOR CONDICIONAL

*if* condição:

expressão

In [42]:
z = 4
if z % 2 == 0: #verdadeiro.
  print('z is even')

z is even


In [43]:
z = 5
if z % 2 == 0: #falso.
  print('checking' + str(z))
  print('z is even')

*if* condição:

expressão

*else*:

expressão

In [44]:
z = 5
if z % 2 == 0: #falso.
  print('z is even')
else:
  print('z is odd')

z is odd


*if* condição:

expressão

*elif* condição:

expressão

*else*:

expressão

In [45]:
z = 3
if z % 2 == 0:
  print('z is divisible by 2') #falso.
elif z % 3 == 0:
  print('z is divisible by 3') #verdadeiro.
else:
  print('z is neither divisible by 2 nor by 3')

z is divisible by 3


#PRATIQUE

1) Na linha 10 verifique que se area for maior que 15 print a mensage : “Big Place”.

2) Apos á verificação, utilize o comando else para informar que se caso contrário, print “pretty small”.

In [46]:
#DEFINE VARIABLES
room = 'kit'
area = 14.0

#IF STATEMENT FOR ROOM
if room == 'kit':
  print('looking around in the kitchen')

#IF STATEMENT FOR AREA
if area > 15:
  print('big place')
else:
  print('pretty small')

looking around in the kitchen
pretty small
