<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/hugo_alexandre/aula07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random as rd
import numpy as np
#geração de números entre 150 e 209
height = range(150,210)

#geração de numeros entre 50 e 149
weight = range(50,150)

#amostra randonica de 20 numeros de height
height = rd.sample(height,20)

#amostra randonica de 20 numeros de weight
weight = rd.sample(weight,20)

#converter height em array e normalizar multiplicando por 0.01
height_array = np.array(height)*0.01
print(height_array)
#converter weight em array
weight_array = np.array(weight)
print(weight)
#calculo do BMI
bmi = weight_array/height_array**2

#verificacao onde bmi é menor que 21
light = bmi<21

#print light
print(light)
#exibicao dos valores de bmi com valor menor que 21
print(bmi[bmi<21])
#print o elementos de weight_array do index 8 ate o index 15,
#incluindo o 15
print(weight_array[8:16])

#print os elemntos height_arra do index 11 ate o index 19,
#incluindo o index 19

[2.01 1.5  1.7  1.67 1.95 1.58 1.57 1.63 1.85 1.64 1.96 1.8  2.04 1.79
 1.55 1.94 2.06 1.97 2.02 2.09]
[81, 89, 103, 123, 134, 90, 63, 132, 52, 84, 101, 98, 51, 66, 128, 142, 58, 102, 147, 125]
[ True False False False False False False False  True False False False
  True  True False False  True False False False]
[20.04900869 15.19357195 12.25490196 20.59860803 13.66764068]
[ 52  84 101  98  51  66 128 142]


In [ ]:
import random as rd
import numpy as np

city1 = [5,10]
city2 = [8,20]
city3 = [4,15]
np_city = np.array([city1,city2,city3])
np_city

np.mean(np_city[:, 0])


np.float64(5.666666666666667)

In [ ]:
np.median(np_city[:, 0])

np.float64(5.0)

In [ ]:
np.corrcoef(np_city[:, 0], np_city[:, 1])

array([[1.        , 0.72057669],
       [0.72057669, 1.        ]])

In [ ]:
np.std(np_city[:, 0])

np.float64(1.699673171197595)

In [ ]:
height = np.round(np.random.normal(1.75,0.20,5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

np_city = np.column_stack((height, weight))
np_city

array([[ 1.76, 54.94],
       [ 1.85, 44.76],
       [ 1.67, 50.34],
       ...,
       [ 2.28, 49.71],
       [ 1.78, 55.53],
       [ 2.01, 72.14]])

In [ ]:
#create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# import numpy package
import numpy as np

#create np_baseball (2 couls)
np_baseball = np.array(baseball)

# print out the 50th row of np_baseball
print(np_baseball[2])
# select the entire second column
#of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]
print(np_weight_lb)
#print out height of 124th player
print(np_baseball[1,0])
media = np.mean(np_baseball[:,0])
print(media)
mediana = np.median(np_baseball[2])
print(mediana)

[210.   98.5]
[ 78.4 102.7  98.5  75.2]
215.0
198.25
154.25


In [ ]:
# Qual linha de comando exibe a documentação da função len()?
# resposta: help(len)

In [ ]:
# Qual dos 3 códigos printa o número 8?

z= np.array ([[9, 9, 3 ],
              [8, 5, 4 ]])
print(z[1,0])

8


In [ ]:
foo = [8.2, 1.7, "A", "Wed", "1.5"]
foo [0:2] = 2.75, -1.5

print(foo)

[2.75, -1.5, 'A', 'Wed', '1.5']


In [ ]:

datascience = "datascience"
datascience.replace("science", "camp")

'datacamp'

In [ ]:

# esse é o código que dá erro
"python" * "2"

TypeError: can't multiply sequence by non-int of type 'str'

In [ ]:
# retorna python data
x = "python"
print( x + " data")

python data


In [ ]:

import numpy as np
np_2d = np.array([[1.5, 6.4, 7.8, 2.2],

[4.3, 8.7, 1.9, 3.4],

[5.3, 7.3, 9.4, 2.5]])

np_2d[2:,2:]

array([[9.4, 2.5]])

In [ ]:
print( "6" * (2**2))

6666


In [ ]:
m = np.array([2, 6, 4])

n = np.array([2, 1, 1])

print(m * n)

[4 6 4]
