<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/hugo_alexandre/aula_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
fam = [1.73, 1.68, 1.71, 1.89]
for height in fam:
    print(height)

1.73
1.68
1.71
1.89


In [ ]:
fam = [1.73, 1.68, 1.71, 1.89]
for index, height in enumerate (fam):
    print("index" + str(index) + ":" +str(height))

index0:1.73
index1:1.68
index2:1.71
index3:1.89


In [ ]:
# print cada item da lista areas utilizando o loop for.
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
for item in areas:
  print(item)

11.25
18.0
20.0
10.75
9.5


In [ ]:

# mude o loop utilizando a função enumerate para exibir o item e o index do item também.

#entender a logica dps
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
for elemento in enumerate(areas):
 print(elemento)

(0, 11.25)
(1, 18.0)
(2, 20.0)
(3, 10.75)
(4, 9.5)


In [ ]:
house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["bedroom", 10.75],
         ["bathroom", 9.50]]
# implemente um loop for para exibir a seguinte saída :
for item in house:
  print(f'the {item[0]} is {item[1]} sqn')


the hallway is 11.25 sqn
the kitchen is 18.0 sqn
the living room is 20.0 sqn
the bedroom is 10.75 sqn
the bathroom is 9.5 sqn


In [ ]:
world = {"afghanistan": 30.55,
         "albania": 2.77,
         "algeria": 39.21}
for key, value in world:
          print(key = '--' + str(value))

ValueError: too many values to unpack (expected 2)

In [ ]:
world = {"afghanistan": 30.55,
         "albania": 2.77,
         "algeria": 39.21}
for key, value in world.items():
   print(key+ "--" + str(value))

afghanistan--30.55
albania--2.77
algeria--39.21


In [ ]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
bmi = np_weight / np_height ** 2
for val in bmi:
   print (val)
# veja a lógica

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


In [ ]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
meas= np.array([np_height, np_weight])
for val in meas:
  print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [ ]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
meas= np.array([np_height, np_weight])
for val in np.nditer(meas):
  print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


In [ ]:
# com auxílio do loop for proporcione seguinte saída :

europe = {'spain':'madrid', 'france':'paris', 'germany': 'berlin', 'norway':'oslo', 'italy':'rome', 'poland': 'warsaw',

'austria': 'vienna' }
for pais, capital in europe.items():
 print (f'the capital of {pais} is {capital}')

the capital of spain is madrid
the capital of france is paris
the capital of germany is berlin
the capital of norway is oslo
the capital of italy is rome
the capital of poland is warsaw
the capital of austria is vienna


In [ ]:
# 1) Crie um array 2D em que possui duas
#linhas: a primeira é o conjunto dos
#números de 1 até 10 e a segunda é o
#conjunto dos números de 11 a 20.

import numpy as np
array= np.array([[1,2,3,4,5,6,7,8,9,10], [11,12,13,14,15,16,17,18,19,20]])

# 2) Com auxilio do loop for mostre cada linha separada

for linha in array:
  print(linha)

# 3) Com auxilio do loop for mostre cada elemento de cada linha.

for linha in array:
  for elemento in linha:
    print(elemento)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
