<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/david_lucasgs/Aula_tarde_30_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [5]:
weight = [65.4, 59.2, 63.6, 88.4, 69.7]
weight

[65.4, 59.2, 63.6, 88.4, 69.7]

In [6]:
height/weight**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [7]:
import numpy as np
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [8]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 69.7])

In [9]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.75337848])

In [10]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [11]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [12]:
numpy_array + numpy_array

array([2, 4, 6])

In [13]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.75337848])

In [15]:
bmi[1]

np.float64(20.97505668934241)

In [14]:
bmi > 23

array([False, False, False,  True, False])

In [16]:
bmi[bmi > 23]

array([24.7473475])

In [17]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [18]:
np_2d.shape

(2, 5)

In [19]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7]])

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

1-a

In [30]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, 68.7]])
np.delete(np_2d, 1, axis=0)

array([[1.73, 1.68, 1.71, 1.89, 1.79]])

1 - b

In [47]:
np_3d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
          [65.4, 59.2, 63.6, 88.4, 68.7]])
nova_linha = [5.5, 6.3, 3.9, 2.8, 9.1]
np_3d = np.append(np_3d, [nova_linha], axis=0)
np_3d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ],
       [ 5.5 ,  6.3 ,  3.9 ,  2.8 ,  9.1 ]])

Não, pois precisa ser a mesma quantidades de colunas para concatenar.

In [48]:
np_3d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
          [65.4, 59.2, 63.6, 88.4, 68.7]])
nova_linha = [5.5, 6.3, 3.9, 2.8]
np_3d = np.append(np_3d, [nova_linha], axis=0)
np_3d

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 4

In [50]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [51]:
np_2d[0][2]

np.float64(1.71)

In [52]:
np_2d[0, 2]

np.float64(1.71)

In [53]:
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [54]:
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

Questão 1

In [62]:
baseball = [180, 215, 210, 210,
            188, 176, 209, 200]

In [56]:
import numpy as np

Questão 2

In [57]:
np_baseball = np.array(baseball)

Questão 3

In [63]:
type(np_baseball)

numpy.ndarray

Questão 4

In [64]:
print(np_baseball.shape)

(8,)
