<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/habacuquidoglas/aula11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd


In [ ]:
dict = {"país":["Brasil","russia","India", "China","Africa do sul"],
        "Capital":["Brasilia", "Moscou","new Delhi", "Beijing","Pretoria"],
        "area":[8.516,17.10,3.287,9.597,1.221],
        "populaçao":[200.4,143.5,1252,1357,52.98]}
brics = pd.DataFrame(dict)
brics.index = ["BR","RU","IN","CH","SA"]
print(brics)

             país    Capital    area  populaçao
BR         Brasil   Brasilia   8.516     200.40
RU         russia     Moscou  17.100     143.50
IN          India  new Delhi   3.287    1252.00
CH          China    Beijing   9.597    1357.00
SA  Africa do sul   Pretoria   1.221      52.98


In [ ]:
#pag 121
names =['estado unidos','australia','japao','india','russia','morocco','egito']
dr =[True,False,False,False,True,True,True]
cpc = [809,731,588,18,200,70,45]
my_dict = {"country":names,"dr":dr,"cpc":cpc}
print(my_dict)

{'country': ['estado unidos', 'australia', 'japao', 'india', 'russia', 'morocco', 'egito'], 'dr': [True, False, False, False, True, True, True], 'cpc': [809, 731, 588, 18, 200, 70, 45]}


In [ ]:
cars = pd.DataFrame(my_dict)
cars.index = ["US","AUS","JPN","IN","RU","MOR","EG"]
print(cars)

           country     dr  cpc
US   estado unidos   True  809
AUS      australia  False  731
JPN          japao  False  588
IN           india  False   18
RU          russia   True  200
MOR        morocco   True   70
EG           egito   True   45


In [ ]:
import pandas as pd


In [ ]:
# pag 122
names =['estado unidos','australia','japao','india','russia','morocco','egito']
dr =[True,False,False,False,True,True,True]
cpc = [809,731,588,18,200,70,45]
my_dict = {"country":names,"dr":dr,"cpc":cpc}
cars_dict ={'country':names,'drives_right':dr,'cars_per_cap':cpc}
row_labels = ['US','AUS','JPN','IN','RU','MOR','EG']
cars = pd.DataFrame(cars_dict)
cars.index = row_labels
print(cars_dict)

{'country': ['estado unidos', 'australia', 'japao', 'india', 'russia', 'morocco', 'egito'], 'drives_right': [True, False, False, False, True, True, True], 'cars_per_cap': [809, 731, 588, 18, 200, 70, 45]}


In [ ]:
#pag 123
cars = pd.read_csv("cars.csv")
print(cars)

  country_ab  cars_per_cap        country  drives_right
0         US           809  United States          True
1        AUS           731      Australia         False
2        JAP           588          Japan         False
3         IN            18          India         False
4         RU           200         Russia          True
5        MOR            70        Morocco          True
6         EG            45          Egypt          True


In [ ]:
#pag 124
cars = pd.read_csv("cars.csv",index_col=0)
print(cars)

            cars_per_cap        country  drives_right
country_ab                                           
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True


In [ ]:
brics["país"]

BR           Brasil
RU           russia
IN            India
CH            China
SA    Africa do sul
Name: país, dtype: object

In [ ]:
type(brics['país'])

pandas.core.series.Series

In [ ]:
brics[["país"]]

país
BR         Brasil
RU         russia
IN          India
CH          China
SA  Africa do sul

In [ ]:
type(brics[["país"]])

pandas.core.frame.DataFrame

In [ ]:
brics[["país","Capital"]]

país    Capital
BR         Brasil   Brasilia
RU         russia     Moscou
IN          India  new Delhi
CH          China    Beijing
SA  Africa do sul   Pretoria

In [ ]:
brics[1:4]

país    Capital    area  populaçao
RU  russia     Moscou  17.100      143.5
IN   India  new Delhi   3.287     1252.0
CH   China    Beijing   9.597     1357.0

In [ ]:
brics.loc["RU"]

país         russia
Capital      Moscou
area           17.1
populaçao     143.5
Name: RU, dtype: object

In [ ]:
brics.loc[["RU"]]

país Capital  area  populaçao
RU  russia  Moscou  17.1      143.5

In [ ]:
brics.loc[["RU","IN","CH"]]

país    Capital    area  populaçao
RU  russia     Moscou  17.100      143.5
IN   India  new Delhi   3.287     1252.0
CH   China    Beijing   9.597     1357.0

In [ ]:
brics.loc[["RU","IN","CH"],["país","Capital"]]

país    Capital
RU  russia     Moscou
IN   India  new Delhi
CH   China    Beijing

In [ ]:
brics.loc[:,["país","Capital"]]

país    Capital
BR         Brasil   Brasilia
RU         russia     Moscou
IN          India  new Delhi
CH          China    Beijing
SA  Africa do sul   Pretoria

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('país').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('Capital').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Capital'].value_counts()
    for x_label, grp in _df_2.groupby('país')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('país')
_ = plt.ylabel('Capital')

In [ ]:
brics.iloc[[1]]

país Capital  area  populaçao
RU  russia  Moscou  17.1      143.5

In [ ]:
brics.iloc[[1,2,3]]

país    Capital    area  populaçao
RU  russia     Moscou  17.100      143.5
IN   India  new Delhi   3.287     1252.0
CH   China    Beijing   9.597     1357.0

In [ ]:
brics.iloc[[1,2,3],[0,1]]

país    Capital
RU  russia     Moscou
IN   India  new Delhi
CH   China    Beijing

In [ ]:
import pandas as pd

In [ ]:
from sklearn.datasets import load_wine
data_wine = load_wine()
df_wine = pd.DataFrame(data_wine.data, columns=data_wine.feature_names)
y = data_wine.target
df_wine['target'] = y
df_wine

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  target  
0                            3.92   1065.0       0  
1                            3.40   1050.0       0  
2                            3.17   1185.0       0  
3                            3.45   1480.0       0  
4                            2.93    735.0       0  
..                            ...      ...     ...  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2  

[178 rows x 14 columns]

In [ ]:
df_wine['alcohol']

0      14.23
1      13.20
2      13.16
3      14.37
4      13.24
       ...  
173    13.71
174    13.40
175    13.27
176    13.17
177    14.13
Name: alcohol, Length: 178, dtype: float64

In [ ]:
df_wine[['alcohol']]

alcohol
0      14.23
1      13.20
2      13.16
3      14.37
4      13.24
..       ...
173    13.71
174    13.40
175    13.27
176    13.17
177    14.13

[178 rows x 1 columns]

In [ ]:
df_wine.loc[2]

alcohol                           13.16
malic_acid                         2.36
ash                                2.67
alcalinity_of_ash                 18.60
magnesium                        101.00
total_phenols                      2.80
flavanoids                         3.24
nonflavanoid_phenols               0.30
proanthocyanins                    2.81
color_intensity                    5.68
hue                                1.03
od280/od315_of_diluted_wines       3.17
proline                         1185.00
target                             0.00
Name: 2, dtype: float64

In [ ]:
df_wine.loc[:2]

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0

#Operadores de comparação

In [7]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([75.4,89.2,63.6,88.4,68.7])
bmi = np_weight / np_height ** 2
bmi


array([25.19295666, 31.60430839, 21.75028214, 24.7473475 , 21.44127836])

In [16]:
if bmi[bmi>30]:
  print("sobrepeso")

sobrepeso


In [25]:
bmi>23
bmi[bmi>23]

array([25.19295666, 31.60430839, 24.7473475 ])

In [33]:
#pag 143 questões 1 a 4
0 == 1

False

In [34]:
2 == 2

True

In [38]:
# questão 2
-5 *15


-75

In [39]:
"pyscript"== "Pyscript"

False

In [40]:
True == 1

True

In [52]:
#pag 144
import numpy as np
my_house = np.array([18.0,20.0,10.75,9.50])
your_house = np.array([14.0,24.0,14.25,9.0])
print(my_house >= 18)
print(my_house < your_house)



[ True  True False False]
[False  True  True False]


In [53]:
my_house[my_house > your_house]

array([18. ,  9.5])

In [54]:
True and True

True

In [55]:
x = 12
x > 5 and x < 15

True

In [56]:
False and True

False

In [59]:
y = 5
y > 7 or y  > 13

False

In [60]:
np.logical_and(bmi > 21, bmi < 22)

array([False, False,  True, False,  True])

In [61]:
bmi[np.logical_and(bmi > 21, bmi < 22)]

array([21.75028214, 21.44127836])

In [64]:
# pag 150
my_kitchen = 18.0
your_kitchen = 14.0
#questão 1
print(my_kitchen > 10 and my_kitchen < 18)


False


In [63]:
#questao 2
print(my_kitchen < 14 or my_kitchen > 17)

True


In [65]:
#quetsão 3
x = my_kitchen * 2
y = my_kitchen * 3
x < y
print(x < y)

True


In [69]:
# pag 151
import numpy as np
my_house = np.array([18.0,20.0,10.75,9.50])
your_house = np.array([14.0,24.0,14.25,9.0])
np.logical_or(my_house > 18.5, my_house < 10)

array([False,  True, False,  True])

In [70]:
np.logical_and(my_house < 11, your_house < 11)

array([False, False, False,  True])

In [71]:
z = 5
if z % 2 == 0:
  print("z é par")
else:
  print("z é impar")

z é impar


In [72]:
z = 10
if z % 2 == 0:
  print("z é par")
else:
  print("z é impar")

z é par


In [73]:
z = 13
if z % 2 == 0:
  print("z é par")
else:
  print("z é impar")

z é impar


In [74]:
z = 5
if z % 3 == 0:
    print("z é multiplo de 3")
elif z % 7 == 0:
    print("z é multiplo de 7")
elif z % 5 == 0:
    print("z é multiplo de 5")
else:
    print("z não é multiplo de 3")

z é multiplo de 5


In [79]:
# pag 153
room = "kit"
area = 14.0
if area > 15:
    print("Big PLace")
else:
  print("pretty small")

pretty small
