<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/Emanuel_Oliveira/aula7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Biblioteca

In [ ]:
pip list

Package                               Version
------------------------------------- -------------------
absl-py                               1.4.0
accelerate                            1.7.0
aiohappyeyeballs                      2.6.1
aiohttp                               3.11.15
aiosignal                             1.3.2
alabaster                             1.0.0
albucore                              0.0.24
albumentations                        2.0.7
ale-py                                0.11.0
altair                                5.5.0
annotated-types                       0.7.0
antlr4-python3-runtime                4.9.3
anyio                                 4.9.0
argon2-cffi                           23.1.0
argon2-cffi-bindings                  21.2.0
array_record                          0.7.2
arviz                                 0.21.0
astropy                               7.1.0
astropy-iers-data                     0.2025.5.19.0.38.36
astunparse                            1

In [ ]:
pip install numpy==2.0.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 66.2 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.1
    Uninstalling numpy-2.0.1:
      Successfully uninstalled numpy-2.0.1


In [ ]:
pip install pydicom

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 34.4 MB/s eta 0:00:00


array

In [3]:
import numpy
array([1,2,3])

NameError: name 'array' is not defined

In [ ]:
numpy.array([1,2,3])

array([1, 2, 3])

In [ ]:
import numpy as np
np([1,2,3])

In [ ]:
from numpy import array
array([1,2,3])

1) Na linha 5 importe a biblioteca math.

2)Calcule o comprimento de uma circunferência e armazene o resultado em C
obs:   Cálculo: C=2.pi.r. A Letra pi é acessível pelo métoho math.pi.

3)Calcule a área da circunferência e armazene o resultado em A: A=pi.r^2

In [7]:
#definition of radius
r = 0.43
#impot the math package
import math as mt
#calculate C
C = 0
C = 2* mt.pi * r
#calculate A
A=0
A = mt.pi * (r*r)
#build printout
print("Circumference:" + str(C))
print("Area:" + str(A))

Circumference:2.701769682087222
Area:0.5808804816487527


Numpy

In [10]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [11]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [12]:
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [13]:
import numpy as np
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [14]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [15]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

Operador soma em array e listas


In [16]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [17]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [18]:
numpy_array + numpy_array

array([2, 4, 6])

Analisando arrays

In [19]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [20]:
bmi[1]

np.float64(20.97505668934241)

In [21]:
bmi > 23

array([False, False, False,  True, False])

In [22]:
bmi[bmi > 23]

array([24.7473475])

Observe que a vírgula entre os colchetes define as linhas do arrays. Realize os seguintes testes:

A) Remova o segundo conjunto de números entre colchetes e print o array novamente.

B) Aumente mais um conjunto de números entre colchetes. É possível linhas com diferentes números de colunas ?


In [23]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [24]:
np_2d.shape

(2, 5)

In [25]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
          [65.4, 59.2, 63.6, 88.4, 68.7]])

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

A)

In [47]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79]])
np_2d

array([[1.73, 1.68, 1.71, 1.89, 1.79]])

B)

In [49]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
          [65.4, 59.2, 63.6, 88.4, 68.7],
          [33.4,21.54,322.7,904.0,565.7]])
np_2d

array([[  1.73,   1.68,   1.71,   1.89,   1.79],
       [ 65.4 ,  59.2 ,  63.6 ,  88.4 ,  68.7 ],
       [ 33.4 ,  21.54, 322.7 , 904.  , 565.7 ]])

Acesso aos elementos de um array


In [50]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [51]:
np_2d[0][2]

np.float64(1.71)

In [52]:
np_2d[0,2]

np.float64(1.71)

In [53]:
np_2d[:, 1:3]

array([[  1.68,   1.71],
       [ 59.2 ,  63.6 ],
       [ 21.54, 322.7 ]])

In [54]:
np_2d[1,:]

array([65.4, 59.2, 63.6, 88.4, 68.7])

1)Importe a biblioteca numpy com acesso via np na linha 6

2)Use np.array() para converter a lista baseball para um array chamado np_baseball.

3)Print o tipo da estrutura de dados np_baseball

4)Print as dimensões do array np_baseball


In [67]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
# Import the numpy package as np
import numpy as np
# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)
# Print out type of np_baseball4
print(type(np_baseball))
#Print as dimensões do array np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(8,)
