<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/laisa_gomes/aula_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Para 1 valor de peso e um valor de altura, print na tela: Você está com sobrepeso se bmi > 30, caso contrário, você esta com peso adequado.
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
for val in bmi:
  if val > 30:
    print('você está acima do peso')
  else:
    print('peso adequado')

peso adequado
peso adequado
peso adequado
peso adequado
peso adequado


In [ ]:
#Para o Array resposta do exemplo ao lado print, usando operador lógico, onde bmi é menor que 23.
print(bmi[bmi>23])

[24.7473475]


In [ ]:
#verifique a igualdade entre duas variáveis booleanas. Nesse caso, True e False.
dois = True
tres = False

print(dois == tres)

False
False
False


In [ ]:
#Verifique se a multiplicação -5 * 15 é igual a 75
a = -5*15
print(a == 75)

In [ ]:
#Verifique se as strings "pyscript" e  "PyScript"  são iguais.
print('pyscript' == 'PyScript')

In [ ]:
#Verfique se a variaável booleana True é igual a 1.
print(True == 1)

In [ ]:
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])
#Print  a verificação de quais elementos são maiores que 18 no array my_house.
print(my_house[my_house >= 18])
#Print  a verificação de quais elementos em my_house são menores que no arrray your_house.
print(my_house [my_house< your_house])

[18. 20.]
[20.   10.75]


In [ ]:
#Modificando valores booleanos
x = 12
x > 5 and x > 15

False

In [ ]:
#Modificando valores
y = 5
y > 7 or y > 13

False

In [ ]:
#Operadores lógicos em array
np.logical_and(bmi > 21, bmi < 22)

array([ True, False,  True, False,  True])

In [ ]:
##Operadores lógicos em array
bmi[np.logical_and(bmi > 21, bmi < 22)]

array([21.85171573, 21.75028214, 21.44127836])

In [ ]:
my_kitchen = 18.0
your_kitchen = 14.0

#verifique se my_kitchen é maior que 10 e menor que 18.
my_kitchen > 10 and my_kitchen < 18

False

In [ ]:
#verifique se my_kitchen é menor que 14 e menor que 17
my_kitchen < 14 and my_kitchen < 17

False

In [ ]:
#Verifique se o dobro de my_kitchen é menor que o triplo de your_kitchen.
my_kitchen*2 < your_kitchen*3

True

In [ ]:
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

array([20. ,  9.5])

In [ ]:
#verifique quais elementos de my_house são maiores que 18.5 ou menores que 10.
my_house[np.logical_or(my_house > 18.5, my_house < 10)]

array([20. ,  9.5])

In [ ]:
#Verifique quis elementos das mesmas posições dos arrays possuem valor menor que 11.
for item in np.logical_and(my_house < 11, your_house < 11):
  print(item)

False
False
False
True


In [ ]:
z = 4
if z % 2 == 0:
  print('z é par')

z é par


In [ ]:
z = 5
if z % 2 == 0:
  print('verificando' + str(z))
  print('z é par')

In [ ]:
z = 3
if z % 2 == 0:
  print('z is divisível por 2')
elif z % 3 == 0:
  print('z é divisível por 3')
else:
  print('z não é divisível por 2 nem por 3')

z é divisível por 3


In [ ]:
room = 'kit'
area = 14.0
if room == 'kit':
  print('looking around in the kitchen.')
elif area > 15:
  print('big place!')
else:
  print('pretty small.')

looking around in the kitchen.
