<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/hugo_alexandre/aula11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
True and True

True

In [ ]:
x = 12
x > 5 and x <15
# TRUE      TRUE


True

In [ ]:
False and True

False

In [ ]:
True and False

False

In [ ]:
False and False

False

In [ ]:
True or True

True

In [ ]:
False or True

True

In [ ]:
True or False

True

In [ ]:
False or False

False

In [ ]:
y = 5
y < 7 or y > 13

True

In [ ]:
not True

False

In [ ]:
not False

True

In [ ]:

import numpy as np

np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])

np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

bmi = np_weight / np_height ** 2

bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [ ]:
bmi > 21

array([ True, False,  True,  True,  True])

In [ ]:
bmi < 22

array([ True,  True,  True, False,  True])

In [ ]:
bmi > 21 and bmi < 22

In [ ]:
np.logical_and(bmi>21, bmi < 22)

array([ True, False,  True, False,  True])

In [ ]:
bmi[np.logical_and(bmi>21, bmi < 22)]

array([21.85171573, 21.75028214, 21.44127836])

In [ ]:
# verifique se my_kitchen é maior que 10 e menor que 18.
my_kitchen = 18.0
your_kitchen = 14.0
np.logical_and(my_kitchen > 10, my_kitchen < 18)

np.False_

In [ ]:
# verifique se my_kitchen é menor que 14 e menor que 17.
np.logical_and(my_kitchen < 14, my_kitchen < 17)

np.False_

In [ ]:
# Verifique se o dobro de my_kitchen é menor que o triplo de your_kitchen.
2*my_kitchen < 3*your_kitchen

True

In [ ]:
# verifique quais elementos de my_house são maiores que 18.5 ou menores que 10.
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0,24.0,14.25,9.0])

print(np.logical_or(my_house > 18.5, my_house< 10))
# Verifique quis elementos das mesmas posições dos arrays possuem valor menor que 11.
print(np.logical_and(my_house<11, your_house<11))

[False  True False  True]
[False False False  True]


In [ ]:


z = 4

if z % 2 ==0:
  print("checking" + str(z))
print("z is even")

checking4
z is even


In [ ]:
z = 5

if z% 2 == 0 :


  print("checking" + str(z))

  print("z is even")

In [ ]:
z = 5

if z% 2 == 0:


  print("z is even")

else:

  print("z is odd")

z is odd


In [ ]:
z=3

if z%2==0:

  print("z is divisible by 2")



elif z% 3==0:

  print("z is divisible by 3")

else:

 print("z is neither divisible by 2 nor by 3")

z is divisible by 3


In [ ]:
room = "kit"
area= 14

#na linha 10 verifique que se area for
#maior que 15 print a mensage : “BigPLace”
if room== "kit":
  print("looking around in the kitchen.")

if area>15:
 print("bigplace")
else:
  print("pretty small")
#2) Apos á verificação, utilize o comando
#else para informar que se caso
#contrário, print “pretty small”.

looking around in the kitchen.
pretty small
