<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/laisa_gomes/aula05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Criar uma lista baseball

baseball = [ 180, 215, 210, 210, 188, 176, 209, 200]

import numpy as np

np_baseball = np.array(baseball)
print( np_baseball)

# Mostrando o tipo
print(type(np_baseball))

# Mostrando as dimensões de np_baseball

print(np_baseball.shape)

[180 215 210 210 188 176 209 200]
<class 'numpy.ndarray'>
(8,)


In [ ]:
import random as rd
import numpy as np

# Geração de números entre 150 e 209
height = range(150, 210)

# Geração de números entre 50 e 149
weight = range(50, 149)

# Amostra  randomica de 20 numeros de height
height_sample = rd.sample(height, 20)

# Amostra  randomica de 20 numeros de weight
weight_sample = rd.sample(weight, 20)

# Converter height em array e normalizar multiplicando poe 0.01
height_array = np.array(height_sample) * 0.01

# Converter weight em array
weight_array = np.array(weight_sample)

# Cálculo do BMI
bmi = weight_array / height_array ** 2

print(bmi)

# Verificação onde BMI é menor que 21
light = bmi<21
print(light)

# Exibição dos valores de bmi com valor menor que 21
print(bmi[light])

# Print os elementos de weight_array do index 8 até o index 15, incluindo o index 15
print(weight_array[8:15])

# Print os elementos height_array do index 11 até o index 19, incluindo o index 19
print(height_array[11:19])

[19.59645812 28.7132112  36.88888889 20.77061308 15.15113255 35.36668176
 37.77117769 36.84210526 34.6318022  15.97567575 20.99054097 47.47732426
 40.61482441 36.27095383 30.02659498 21.60493827 43.97978473 19.460881
 13.63720414 27.85297793]
[ True False False  True  True False False False False  True  True False
 False False False False False  True  True False]
[19.59645812 20.77061308 15.15113255 15.97567575 20.99054097 19.460881
 13.63720414]
[129  62  79 134 116 148 105]
[1.68 1.69 2.02 1.87 1.8  1.61 1.95 2.08]


In [ ]:
import random as rd
import numpy as np

In [ ]:
city1 = [5, 10]
city2 = [8, 20]
city3 = [4, 15]

In [ ]:
import random as rd
dados =  np.random.randit(1, 100, 100)
dados

AttributeError: module 'numpy.random' has no attribute 'randit'

In [ ]:
import matplotlib.pyplot as plt
plt.hist(dados)

NameError: name 'dados' is not defined