<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/levi_nascimento/Aula_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BIBLIOTECAS

In [ ]:
# pip list - mostrar as bibliotecas instaladas
pip list

Package                               Version
------------------------------------- -------------------
absl-py                               1.4.0
accelerate                            1.7.0
aiohappyeyeballs                      2.6.1
aiohttp                               3.11.15
aiosignal                             1.3.2
alabaster                             1.0.0
albucore                              0.0.24
albumentations                        2.0.7
ale-py                                0.11.0
altair                                5.5.0
annotated-types                       0.7.0
antlr4-python3-runtime                4.9.3
anyio                                 4.9.0
argon2-cffi                           23.1.0
argon2-cffi-bindings                  21.2.0
array_record                          0.7.2
arviz                                 0.21.0
astropy                               7.1.0
astropy-iers-data                     0.2025.5.19.0.38.36
astunparse                            1

In [ ]:
pip install numpy==2.0.1

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 89.5 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: Operation cancelled by user


In [ ]:
pip install numpy==2.0.2


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 43.2 MB/s eta 0:00:00


In [ ]:
pip install pydicom

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 25.4 MB/s eta 0:00:00


BIBLIOTECA NUMPY

In [ ]:
import numpy
array([1, 2, 3])

NameError: name 'array' is not defined

In [3]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
from numpy import array
array([1, 2, 3])

array([1, 2, 3])

PRATIQUE

In [ ]:
# definindo raio
r = 0.43

#1) importe a biblioteca math
import math

#2)Calcule o comprimento de uma circunferência e armazene o resultado em C
#obs:   Cálculo
#A Letra pi é acessível pelo métoho math.pi.
c = 0
c = 2 *math.pi * r

#3)Calcule a área da circunferência e armazene o resultado em A
a = 0
a = math.pi*r

#print resultados
print("Circuferência: " + str(c))
print("Área: " + str(a))

Circuferência: 2.701769682087222
Área: 1.350884841043611


NUMPY

In [ ]:
heigth = [1.73, 1.68, 1.71, 1.89, 1.79]
heigth

[1.73, 1.68, 1.71, 1.89, 1.79]

In [ ]:
weigth = [65.4, 59.2, 63.6, 88.4, 68.7]
weigth

[65.4, 59.2, 63.6, 88.4, 68.7]

In [ ]:
weigth / heigth **2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
import numpy as np
np_height = np.array(heigth)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [ ]:
np_weigthq = np.array(weigth)
np_weigthq

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [ ]:
bm1 = np_weigthq / np_height **2
bm1

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

OPERADOR SOMA EM ARRAY E LISTAS

In [ ]:
python_list = [1, 2, 3]
nump_array = np.array([1, 2, 3])

In [ ]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [ ]:
nump_array + nump_array

array([2, 4, 6])

ANALISANDO ARRAYS

In [ ]:
bm1

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [ ]:
bm1[1]

np.float64(20.97505668934241)

In [ ]:
bm1 > 23

array([False, False, False,  True, False])

In [ ]:
bm1[bm1 > 23]

array([24.7473475])

NUMPY

In [5]:
#Observe que a vírgula entre os colchetes define as linhas do arrays. Realize os seguintes testes:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [6]:
#a) Remova o segundo conjunto de números entre colchetes e print o array novamente.
np_2d = np.array(np_2d[0])


In [ ]:
np.array([['1.73', '1.68', '1.71', '1.89', '1.79'],
          ['65.4', '59.2', '63.6', '88.4', '68.7']])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U4')

In [2]:
#b)Aumente mais um conjunto de números entre colchetes. É possível linhas com diferentes números de colunas?
np_2d = np.array (([1.73, 1.68, 1.71, 1.89, 1.79]
                   [65.4, 59.2, 63.6, 88.4, '68.7']))

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-2-577c1d3eea3e>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  np_2d = np.array (([1.73, 1.68, 1.71, 1.89, 1.79]


NameError: name 'np' is not defined

Acesso aos elementos de um array

In [ ]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [ ]:
print(np_2d[0][2])
#ou
print(np_2d[0, 2])

1.71
1.71


In [ ]:
print(np_2d[:, 1:3])

[[ 1.68  1.71]
 [59.2  63.6 ]]


In [ ]:
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

PRATIQUE

In [ ]:
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

#1) importe a biblioteca numpy com acesso via np
import numpy as np

#2) Use np.array() para converter a lista baseball para um array chamado np_baseball.
np_baseball = np.array(baseball)

#3) Print o tipo da estrutura de dados np_baseball
print(type(np_baseball))

#4) Print as dimensões do array np_baseball
print(np_baseball)

<class 'numpy.ndarray'>
[180 215 210 210 188 176 209 200]
