<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/cauanrodrigues/aula6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importando bibliotecas no python

In [ ]:
pip install pydicom

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 13.0 MB/s eta 0:00:00


In [ ]:
pip install numpy

In [ ]:
import numpy
array([1,2,3])

In [ ]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
numpy.array([1,2,3])

In [ ]:
from numpy import array
array([1,2,3])

array([1, 2, 3])

QUESTÕES 1,2 e 3

In [9]:
#Definition of radius
r = 0.43

#Import the math package
import math

#Calculate C
p = math.pi
C = 2 * p * r
print(C)

#Calculate A
A = p * r**2
print(A)

2.701769682087222
0.5808804816487527


Utilizando a biblioteca numpy

In [ ]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

In [ ]:
weight = [65.4, 58.2, 63.6, 88.4, 68.7]
weight

In [ ]:
weight / height ** 2

In [ ]:
import numpy as np
np_height = np.array(height)
np_height

In [ ]:
np_weight = np.array(weight)
np_weight

In [ ]:
bmi = np_weight / np_height ** 2
bmi

Operador soma em array e listas

In [ ]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [ ]:
python_list = python_list

In [ ]:
numpy_array + numpy_array

Analisando Arrays

In [ ]:
bmi

In [ ]:
bmi[1]

In [ ]:
bmi > 23

In [ ]:
bmi[bmi > 23]

Modificando arrays

In [ ]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

In [31]:
np_2d.shape

(1, 5)

Testes

In [22]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79]])
np_2d

array([[1.73, 1.68, 1.71, 1.89, 1.79]])

In [18]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, 68.7],
                  [1.09]])
np_2d.shape
#Não é possivel pois o programa requer uma sequencia que é definida na primeiralinha e ele não interpreta apenas um numero como linha
#Forma correta:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, 68.7],
                  [1.09, 10, 1, 2 ,3]])

(3, 5)

Acessando os elementos de um array

In [23]:
np_2d[0]
np_2d[2]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [ ]:
np_2d[0][2]
np_2d[1][2]

In [24]:
np_2d[0, 2]
np_2d[1, 4]

np.float64(1.71)

In [26]:
np_2d[:, 1:3]

array([[1.68, 1.71]])

In [30]:
np_2d[0, :]

array([1.73, 1.68, 1.71, 1.89, 1.79])

QUESTÕES 1,2,3 e 4

In [10]:
#Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

#Import the numpy package as np
import numpy as np

#Create a numpy array from baseball:
#np_baseball
np_baseball = np.array([baseball])

#Print out type of np_baseball
type(np_baseball)


numpy.ndarray