<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/antonio_erick/aula_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
fam= [1.73,1.68,1.71,1.89]
for height in fam:
  print(height)

1.73
1.68
1.71
1.89


In [6]:
#LOOP FOR
fam= [1.73,1.68,1.71,1.89]
for index,height in enumerate(fam):
  print(f'index {index}: {height}')

index 0: 1.73
index 1: 1.68
index 2: 1.71
index 3: 1.89


In [10]:
#1) Print cada item da lista areas utilizando o loop for.
areas= [11.25,18.0,20.0,10.75,9.50]
for area in areas:
  print(f'{area}')

11.25
18.0
20.0
10.75
9.5


In [18]:
#1)mude o loop utilizando a função enumerate para exibir o item e o index do item também.
areas= [11.25,18.0,20.0,10.75,9.50]
for index, item in enumerate(areas):
  print(f"index {index} : {item}")

#outra forma de fazer:
areas= [11.25,18.0,20.0,10.75,9.50]
for item in areas:
  print(areas.index(item),item)


index 0 : 11.25
index 1 : 18.0
index 2 : 20.0
index 3 : 10.75
index 4 : 9.5
0 11.25
1 18.0
2 20.0
3 10.75
4 9.5


In [20]:
# implemente um loop for para exibir a seguinte saída :
house=[['hallaway', 11.25],
       ['kitchen',18.0],
       ['living room', 20.0],
       ['bedroom', 10.75],
       ['bathroom', 9.50]]
for item in house:
  print(f'the {item[0]} is {item[1]} sqm')

the hallaway is 11.25
the kitchen is 18.0
the living room is 20.0
the bedroom is 10.75
the bathroom is 9.5


In [21]:
#Loop em dicionário - erro!

world={'afghanistan':30.55,
      'albania':2.77,
      'algeria':39.21}
for key, value in world:
  print(key + '--' + str (value))


ValueError: too many values to unpack (expected 2)

In [22]:
#Loop em dicionário

world={'afghanistan':30.55,
      'albania':2.77,
      'algeria':39.21}
for key, value in world.items():
  print(key + '--' + str(value))


afghanistan--30.55
albania--2.77
algeria--39.21


In [34]:
#Loop em Numpy
import numpy as np
np_height= np.array ([1.73,1.68,1.71,1.89,1.79])
np_weight= np.array ([65.4,59.2,63.6,88.4,68.7])
bmi= np_weight/np_height**2
for val in bmi :
  print(val)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


In [24]:
#Loop em numpy 2D
import numpy as np
np_height= np.array ([1.73,1.68,1.71,1.89,1.79])
np_weight= np.array ([65.4,59.2,63.6,88.4,68.7])
meas= np.array([np_height,np_weight])
for val in meas:
  print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [25]:
#Loop em numpy 2D
import numpy as np
np_height= np.array ([1.73,1.68,1.71,1.89,1.79])
np_weight= np.array ([65.4,59.2,63.6,88.4,68.7])
meas= np.array([np_height, np_weight])
for val in np.nditer(meas):
  print(val )

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


In [27]:
#com auxílio do loop for proporcione  seguinte saída :
europe={'spain':'madrid','france':'paris','germany':'berlin',
       'norway':'oslo','italy':'rome','poland':'warsaw','austria':'vienna'}
for key, capital in europe.items():
  print(f'the capital of {key} is {capital}')

the capital of spain is madrid
the capital of france is paris
the capital of germany is berlin
the capital of norway is oslo
the capital of italy is rome
the capital of poland is warsaw
the capital of austria is vienna


In [36]:
import numpy as np
np_um_a_dez=np.array([1,2,3,4,5,6,7,8,9,10])
np_onze_a_vinte=np.array([11,12,13,14,15,16,17,18,19,20])
#Crie um array 2D em que possui duas linhas: a primeira é o conjunto dos números de 1 até 10 e a segunda é o conjunto dos números de 11 a 20.
array2d=np.array([np_um_a_dez,np_onze_a_vinte])
#Com auxilio do loop for mostre cada linha separada
for item in array2d:
  print(item)
#Com auxilio do loop for mostre cada elemento de cada linha.
for val in np.nditer(array2d):
  print(val)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
