<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/yana_karen/Aula6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random as rd

In [2]:
import numpy as np

In [55]:
height = list(range(150,210))
height

[150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209]

In [59]:
weight = list(range(50,149))
weight

[50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148]

In [60]:
height = rd.sample(height,20)
height

[171,
 197,
 151,
 187,
 184,
 170,
 204,
 165,
 202,
 155,
 159,
 192,
 156,
 176,
 181,
 194,
 161,
 209,
 150,
 191]

In [61]:
weight = rd.sample(weight,20)
weight

[105,
 120,
 51,
 80,
 111,
 71,
 97,
 112,
 66,
 82,
 73,
 134,
 144,
 76,
 114,
 64,
 143,
 89,
 61,
 60]

In [62]:
height_array = np.array(height) * 0.01
height_array

array([1.71, 1.97, 1.51, 1.87, 1.84, 1.7 , 2.04, 1.65, 2.02, 1.55, 1.59,
       1.92, 1.56, 1.76, 1.81, 1.94, 1.61, 2.09, 1.5 , 1.91])

In [63]:
weight_array = np.array(weight)
weight_array

array([105, 120,  51,  80, 111,  71,  97, 112,  66,  82,  73, 134, 144,
        76, 114,  64, 143,  89,  61,  60])

In [64]:
bmi = weight_array / (height_array ** 2)
bmi

array([35.90848466, 30.92066273, 22.36744002, 22.8774057 , 32.78591682,
       24.56747405, 23.30834295, 41.13865932, 16.17488482, 34.13111342,
       28.87544005, 36.34982639, 59.17159763, 24.53512397, 34.7974726 ,
       17.00499522, 55.16762471, 20.37499142, 27.11111111, 16.44691757])

In [67]:
light = bmi < 21
light

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True, False,  True,
       False,  True])

In [68]:
bmi[light]

array([16.17488482, 17.00499522, 20.37499142, 16.44691757])

In [69]:
weight_array[8:16]

array([ 66,  82,  73, 134, 144,  76, 114,  64])

In [70]:
height_array[11:20]

array([1.92, 1.56, 1.76, 1.81, 1.94, 1.61, 2.09, 1.5 , 1.91])