<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/Emanuel_Oliveira/aula8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lâmina 68:

In [23]:
import random as rd
import numpy as np
#geração de numeros entre 150 e 209
height = range(150,210)
print(height)
#geração de numeros entre 50 e 149
weight = range(50,150)
print(weight)
#amostra randomica de 20 numeros de height
height = rd.sample(height,20)
#amostra randomica de 20 numeros de weight
weight = rd.sample(weight,20)
#converter height em array e normalizar multiplicando por 0.01
height_array = np.array([height])*0.01
print(height_array)
#conversor de weight em array
weight_array = np.array([weight])
print(weight_array)
#calculo do BMI
bmi = (weight_array/(height_array**2))
print(bmi)
#verificação onde BMI é menor que 21
light = bmi < 21
#print light
print(light)
#exibiçao dos valores de bmi com valor menor que 21
print(bmi[light])
#Print o elementos de weight_array do index 8 até o index 15, incluindo o index 15
print(weight_array[8:16])
#Print os elementos height_arra do index 11 até o index 19, incluindo o index 19
print(height_array[11:20])

range(150, 210)
range(50, 150)
[[1.94 1.75 1.79 1.64 1.56 2.01 1.76 1.86 1.9  1.6  2.07 2.09 1.61 1.65
  2.02 2.03 2.08 1.66 1.5  1.83]]
[[148 147  64  52  50  69 138 145 128 122  77 140  81  54 115  89  82 116
  129  84]]
[[39.32405144 48.         19.97440779 19.33372992 20.54569362 17.07878518
  44.55061983 41.91235981 35.45706371 47.65625    17.97008098 32.05054829
  31.24879441 19.83471074 28.18351142 21.59722391 18.95340237 42.09609522
  57.33333333 25.08286303]]
[[False False  True  True  True  True False False False False  True False
  False  True False False  True False False False]]
[19.97440779 19.33372992 20.54569362 17.07878518 17.97008098 19.83471074
 18.95340237]
[]
[]


Lâmina 69 e 70:

In [31]:
import random as rd
import numpy as np
city1 = [5,10]
city2 = [8,20]
city3 = [4,15]
np_city = np.array([city1,city2,city3])

In [32]:
np.mean(np_city[:, 0])

np.float64(5.666666666666667)

In [33]:
np.median(np_city[:, 0])

np.float64(5.0)

In [34]:
np.corrcoef(np_city[:, 0], np_city[:, 1])

array([[1.        , 0.72057669],
       [0.72057669, 1.        ]])

In [35]:
np.std(np_city[:, 0])

np.float64(1.699673171197595)

Geração de um array randômico

In [36]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))

1)Print a terceira linha de np_baseball na linha 14 do código.

2)Crie uma nova variável np_weight_lb que recebe toda a segunda coluna de np_baseball.

3)Print a primeira coluna da segunda linha de Np_baseball na linha  do código.

4)Calcule e exiba a média da primeira coluna de np_baseball.

5)Calcule e exiba a mediana da segunda linha de np_baseball.


In [46]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]
# Import numpy package
import numpy as np
# Create np_baseball (2 cols)
np_baseball = np.array (baseball)
# Print out the 50th row of np_baseball
print(np_baseball[2])
# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]
# Print out height of 124th player
print(np_baseball[1,0])
#Calcule e exiba a média da primeira coluna de np_baseball.
media = np.mean(np_baseball[:,0])
print(media)
#Calcule e exiba a mediana da segunda linha de np_baseball.
mediana = np.median(np_baseball[1])
print(mediana)

[210.   98.5]
215.0
198.25
158.85


1) Qual linha de comando exibe a documentação da função len()


In [48]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



2) Qual dos 3 códigos printa o número 8?


In [49]:
import numpy as np
z = np.array([[9, 9, 3],
              [8, 5, 4]])
print(z[1, 0])

8


Lâmina 75:

In [50]:
foo = [0.2, 1.7, "A", "Wed", "1.5"]
foo[0:2] = [2.75, -1.5]
print(foo)

[2.75, -1.5, 'A', 'Wed', '1.5']


Lâmina 76:

In [51]:
"datascience".replace("science","camp")

'datacamp'

5) Qual linha de código apresenta erro ?


In [52]:
"python" * "2"

TypeError: can't multiply sequence by non-int of type 'str'

6) Qual código retorna o texto:
 python data

In [54]:
x = "python"
print(x + " data")

python data


7) Considerando esse código
np_2d = np.array
                   ([[1.5, 6.4, 7.8, 2.2],

                    [4,3, 8,7, 1,9, 3,4],

                    [5.3, 7.3, 9.4, 2.5]])

:Qual opção ao lado representa o comando:

np_2d[2:,2:]

5.3

4.3

array([[9.4, 2.5]])

In [62]:
import numpy as np
np_2d = np.array ([
                  [1.5, 6.4, 7.8, 2.2],
                  [4.3, 8.7, 1.9, 3.4],
                  [5.3, 7.3, 9.4, 2.5]
                  ])

In [63]:
np_2d[2:,2:]

array([[9.4, 2.5]])

8) Complete o código para a saída 6666


In [67]:
print("6"*(2 ** 2))

6666
