<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/hugo_alexandre/Aula10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])

np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

bmi = np_weight / np_height ** 2

print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [ ]:
bmi > 23

array([False, False, False,  True, False])

In [ ]:
bmi[bmi >23]

array([24.7473475])

In [ ]:
2 < 3

True

In [ ]:
2 == 3

False

In [ ]:
2<=3

True

In [ ]:
3<=3

True

In [ ]:
x= 2
y= 3
x < y

True

In [ ]:
"carl" < "chris"

True

In [ ]:
3 < "Chris"

TypeError: '<' not supported between instances of 'int' and 'str'

In [ ]:
3<4.1

True

In [ ]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [ ]:
bmi > 23

array([False, False, False,  True, False])

In [ ]:
# 1) verifique a igualdade entre duas variáveis
# booleanas. Nesse caso, True e False.
True == False



# 4) Verfiue se a variaável booleana True é
# igual a 1.

False

In [ ]:
# 2) Verifique se a multiplicação -5 * 15 é igual
# a 75
-5*15 == 75

False

In [ ]:
# 3) Verifique se as strings "pyscript" e
# "PyScript" são iguais.

"pyscript" == "PyScript"

False

In [ ]:
True == 1

True

In [ ]:
import numpy as np

my_house = np.array([18.0, 20.0, 10.75, 9.50])

your_house = np.array([14.0, 24.0, 14.25, 9.0])

# Print a verificação de quais elementos são maiores que 18 no array my_house.
print(my_house > 18)
print(my_house < your_house)

[False  True False False]
[False  True  True False]
