<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/joao_pedro/Aula11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.altura = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np.peso = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
imc = np.peso/ np.altura **2
print(imc[imc > 23])
print(imc[imc < 23])

[24.7473475]
[21.85171573 20.97505669 21.75028214 21.44127836]


In [ ]:
import numpy as np

altura = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
peso = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
imc = peso / altura ** 2

In [ ]:
if imc.all() > 30:
    print('Sobrepeso')
    print(imc[imc > 30])
else:
    print('Não está acima do peso')
    print(imc[imc < 30])

Não está acima do peso
[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [ ]:
imc < 23
imc[imc < 23]

array([21.85171573, 20.97505669, 21.75028214, 21.44127836])

In [ ]:
True == False

False

In [ ]:
-5 * 15 == 75

False

In [ ]:
'pyscipt' == 'PyScript'

False

In [ ]:
True == 1

True

In [ ]:
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

In [ ]:
my_house > your_house

array([ True, False, False,  True])

In [ ]:
my_house[my_house > 18]

array([20.])

In [ ]:
my_house[my_house > your_house]

array([18. ,  9.5])

In [ ]:
y = 5
y < 7 and y > 13

False

In [ ]:
imc

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [ ]:
np.logical_and(imc > 21, imc < 22)

array([ True, False,  True, False,  True])

In [ ]:
imc[np.logical_and(imc > 21, imc < 22)]

array([21.85171573, 21.75028214, 21.44127836])

In [ ]:
my_kitchen = 18.0
your_kitchen = 14.0

In [ ]:
my_kitchen > 10 and my_kitchen < 18

False

In [ ]:
my_kitchen > 14 and my_kitchen < 17

False

In [ ]:
my_kitchen*2 < your_kitchen*3

True

In [ ]:
my_house.all() > 18.5 or my_house.all() < 10
print(my_house[my_house > 18.5])
print(my_house[my_house < 10])

[20.]
[9.5]


In [ ]:
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

In [ ]:
np.logical_and(my_house < 11, your_house < 11)

array([False, False, False,  True])

In [ ]:
z = 4
if z % 2 == 0:
    print('z é par')

z é par


In [ ]:
z = 3
if z % 2 == 0:
    print('z é par')
elif z % 3 == 0:
    print('z é divisível por 3')
else:
    print('z não é par nem divisível por 3')

z é divisível por 3


In [ ]:
room = 'kit'
area = 14.0
if room == 'kit':
  print('Looking around in the kitchen')
if area > 15:
  print('big place!')
else:
  print('pretty small')


Looking around in the kitchen
pretty small
