<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/laisa_gomes/aula_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy==2.0.1


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 56.0 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2


In [ ]:
pip install numpy==2.0.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 89.3 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.1
    Uninstalling numpy-2.0.1:
      Successfully uninstalled numpy-2.0.1


In [ ]:
pip install pydicom

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 35.4 MB/s eta 0:00:00


In [ ]:
import numpy
array ([1,2,3])

NameError: name 'array' is not defined

In [ ]:
numpy.array([1,2,3])

array([1, 2, 3])

In [ ]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
from numpy import array
array([1,2,3])

array([1, 2, 3])

In [ ]:
# Usando biblioteca math

import math

# Calculando circuferência

r= 0.43
c= 2*math.pi*r

print("Circuferência: " + str(c))

# Calculando área
a= math.pi*r**2
print("Área é: " + str(a))

Circuferência: 2.701769682087222
Área é; 0.5808804816487527


In [ ]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

weight/ height**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
import numpy as np
np_height = np.array(height)
np_height

np_weight = np.array(weight)
np_weight

bmi = np_weight/ np_height**2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [ ]:
python_list = [1,2,3]
numpy_array = np.array([1,2,3])

print(python_list + python_list)
print(numpy_array + numpy_array)

In [ ]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [ ]:
bmi[1]

In [ ]:
bmi > 23

array([False, False, False,  True, False])

In [ ]:
bmi[bmi > 23]

array([24.7473475])

In [ ]:
import numpy as np
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, "68.7"]])
print(np_2d)

np_2d.shape # Mostra a quantidade de linha e colunos

[['1.73' '1.68' '1.71' '1.89' '1.79']
 ['65.4' '59.2' '63.6' '88.4' '68.7']]


(2, 5)

In [ ]:
np_2d = np.array(np_2d[0]) # O array não apaga o segundo conjunto de números
print(np_2d)

['1.73' '1.68' '1.71' '1.89' '1.79']


In [ ]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], # Não dá para adicionar mais nenhuma coluna de números, o array não permite
                  [65.4, 59.2, 63.6, 88.4, "68.7"]])

In [ ]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, 68.7]])

In [ ]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [ ]:
print(np_2d[0, 2])

1.71


In [ ]:
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [ ]:
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])