<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/saulo_brito/aula_da_trade_dia_30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [5]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [6]:
weight / height

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [7]:
import numpy as np
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [8]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [9]:
bm1 = np_weight / np_height ** 2
bm1

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [10]:
#___________________________________________________________________________________________

In [11]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [12]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [13]:
numpy_array + numpy_array

array([2, 4, 6])

In [14]:
#______________________________________________________________________________

In [15]:
bm1

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [16]:
bm1[1]

np.float64(20.97505668934241)

In [17]:
bm1 > 23

array([False, False, False,  True, False])

In [18]:
bm1[bm1 > 23]

array([24.7473475])

In [19]:
#_________________________________________________________________________________________

In [20]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [21]:
np_2d.shape

(2, 5)

In [22]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, "68.7"]])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [23]:
#_________________________________________________________________________________

In [24]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [25]:
#_____________________________________________________________________________________

In [26]:
np_2d[0][2]

np.float64(1.71)

In [27]:
np_2d[0, 2]

np.float64(1.71)

In [28]:
#____________________________________________________________________________________________

In [29]:
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [30]:
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])