<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/levi_nascimento/Aula_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

OPERADORES DE COMPARAÇÃO

In [8]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height**2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [14]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height**2
bmi

#Para 1 valor de peso e um valor de altura, print na tela: Você está com sobrepeso se bmi > 30, caso contrário, você esta com peso adequado.
for valor in bmi:
  if valor > 30:
    print(valor, " Você está com sobrepeso")
  else:
    print(valor, " Você está com peso adequado")

21.85171572722109  Você está com peso adequado
20.97505668934241  Você está com peso adequado
21.750282138093777  Você está com peso adequado
24.74734749867025  Você está com peso adequado
21.44127836209856  Você está com peso adequado


In [16]:
#Para o Array resposta do exemplo ao lado print, usando operador lógico, onde bmi é menor que 23.
bmi[bmi < 23]

array([21.85171573, 20.97505669, 21.75028214, 21.44127836])

PRATIQUE

In [22]:
#verifique a igualdade entre duas variáveis booleanas. Nesse caso, True e False.
verdade = True
mentira = False
print( verdade == mentira)

#Verifique se a multiplicação -5 * 15 é igual a 75
print(-5 * 15 == 75)

#Verifique se as strings "pyscript" e  "PyScript"  são iguais.
print("pyscript" == "PyScript")

#Verifique se a variaável booleana True é igual a 1.
print(True == 1)

False
False
False
True


In [27]:
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

#Print a verificação de quais elementos são maiores que 18 no array my_house.
my_house[my_house > 18]

#Print  a verificação de quais elementos em my_house são menores que no arrray your_house.
print(my_house[my_house < your_house])

[20.   10.75]


OPERADORES BOOLEANOS

In [28]:
x = 12
x > 5 and x < 11

False

In [29]:
y = 5
y < 4 or y > 6

False

In [30]:
#logical_and()
#logical_or()
#logical_not()

np.logical_and(bmi > 21, bmi < 22)

array([ True, False,  True, False,  True])

In [31]:
bmi[np.logical_and(bmi > 21, bmi < 22)]

array([21.85171573, 21.75028214, 21.44127836])

PRATIQUE


In [35]:
my_kitchen = 18.0
your_kitchen = 14.0

#verifique se my_kitchen é maior que 10 e menor que 18.
print(np.logical_and(my_kitchen > 10, my_kitchen <18))

#verifique se my_kitchen é menor que 14 e menor que 17.
print(np.logical_and(my_kitchen < 14, my_kitchen < 17))

#Verifique se o dobro de my_kitchen é menor que o triplo de your_kitchen.
print(my_kitchen*2 < your_kitchen*3)


False
False
True


In [46]:
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

#verifique quais elementos de my_house são maiores que 18.5 ou menores que 10.
print(my_house[np.logical_or(my_house > 18.5, my_house < 10.0)])

#Verifique quais elementos das mesmas posições dos arrays possuem valor menor que 11.
np.logical_and(my_house < 11, your_house < 11)


[20.   9.5]


array([False, False, False,  True])

CONDICIONAL

In [50]:
z = 10
if z % 2 == 0:
  print("Z é par")
else:
  print("Z é ímpar")

Z é par


In [54]:
z = 7
if z % 2 == 0:
  print("Z é divisível por 2")
elif z % 3 == 0:
  print("Z é divisível por 3")
else:
  print("Z não é divisível nem por 2 nem por 3")

Z não é divisível nem por 2 nem por 3


PRATIQUE

In [ ]:
room = 'kit'
area = 14.0

#verifique que se area for maior que 15 print a mensage : “Big PLace”
#Apos á verificação, utilize o comando else para informar que se caso contrário, print “pretty small”.
if area > 15:
  print("Big Place")
else:
  print("pretty small")