<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/kauan_lima/aula_11_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pratique

In [3]:
#1
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
for area in areas:
  print(area)

11.25
18.0
20.0
10.75
9.5


In [8]:
#2
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
for index, area in enumerate(areas):
  print("index " + str(index) + ": " + str(area))

index 0: 11.25
index 1: 18.0
index 2: 20.0
index 3: 10.75
index 4: 9.5


In [18]:
#3
house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["badroom", 10.75],
         ["bathroom", 9.50]]
for room in house:
  print("the " + str(room[0]) + " is " + str(room[1]) + " sqm")

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the badroom is 10.75 sqm
the bathroom is 9.5 sqm


In [19]:
world = { "afghanistan":30.55,
          "albania":2.77,
          "algeria":39.21 }
for key, value in world.items():
  print(key + " -- " + str(value))


afghanistan -- 30.55
albania -- 2.77
algeria -- 39.21


In [20]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
for val in bmi:
  print(val)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


In [21]:
meas = np.array([np_height, np_weight])
for val in meas:
  print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [22]:
meas = np.array([np_height, np_weight])
for val in np.nditer(meas):
  print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


In [29]:
euroupe = {'spain':'madrid', 'france':'paris', 'germany':'berlin',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw', 'austria':'vienna'}
for keys, values in europe.items():
  print("the capital of " + keys + " is " + values)

the capital of spain is madrid
the capital of france is paris
the capital of germany is berlin
the capital of norway is oslo
the capital of italy is rome
the capital of poland is warsaw
the capital of austria is vienna


Pratique

In [34]:
#1
import numpy as np
n1=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
n2=np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
#2
n= np.array([n1, n2])
for val in n:
  print(val)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [36]:
#3
n= np.array([n1, n2])
for val in np.nditer(n):
  print(val)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
