<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/Emanuel_Oliveira/aula12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercício:

1)Para 1 valor de peso e um valor de altura, print na tela: Você está com sobrepeso se bmi > 30, caso contrário, você esta com peso adequado.

2)Para o Array resposta do exemplo ao lado print, usando operador lógico, onde bmi é menor que 23.


In [1]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [2]:
bmi > 23

array([False, False, False,  True, False])

In [3]:
bmi[bmi > 23]

array([24.7473475])

In [8]:
#1)
if bmi.all() > 30:
  print("você está com sobrepeso")
else:
  print("você está com o peso adequdo")

você está com o peso adequdo


In [10]:
#2)
bmi < 23

array([ True,  True,  True, False,  True])

In [11]:
bmi[bmi<23]

array([21.85171573, 20.97505669, 21.75028214, 21.44127836])

1)verifique a igualdade entre duas variáveis booleanas. Nesse caso, True e False.

2)Verifique se a multiplicação -5 * 15 é igual a 75

3)Verifique se as strings "pyscript" e  "PyScript"  são iguais.

3)Verfiue se a variaável booleana True é igual a 1.


In [21]:
# Comparison of booleans
a = 1
b = 2
c = a == b
print(c)
# Comparison of integers
d = -5
e = 15
mult = d * e
compar = mult == 75
print(compar)
# Comparison of strings
str1 = "pyscript"
str2 = "PyScript"
comparacao = str1 == str2
print(comparacao)
# Compare a boolean with an integer
True == 1

False
False
False


True

1)Print  a verificação de quais elementos são maiores que 18 no array my_house.

2)Print  a verificação de quais elementos em my_house são menores que no arrray your_house.


In [ ]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])
#my_house greater than or equal to 18

#my_house less than your_house


In [22]:
x = 12
x > 5 and x < 15

True

In [23]:
x = 15
x > 5 and x < 15

False

In [24]:
y = 5
y < 7 or y > 13

True

In [25]:
y = 7
y < 7 or y > 13

False

In [26]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [27]:
np.logical_and(bmi > 21, bmi < 22)

array([ True, False,  True, False,  True])

In [28]:
bmi[np.logical_and(bmi > 21, bmi < 22)]

array([21.85171573, 21.75028214, 21.44127836])

1)verifique se my_kitchen é maior que 10 e menor que 18.

2)verifique se my_kitchen é menor que 14 e menor que 17.

3)Verifique se o dobro de my_kitchen é menor que o triplo de your_kitchen.


In [34]:
# Define variables
my_kitchen = 18.0
your_kitchen = 14.0
#my_kitchen bigger than 10 and smaller than 18?
print(my_kitchen > 10 and my_kitchen < 18)
# my_kitchen smaller than 14 or bigger than 17?
print(my_kitchen > 14 and my_kitchen < 17)
# Double my_kitchen smaller than triple your_kitchen?
dobro_my_kitchen = my_kitchen*2
print(dobro_my_kitchen)
triplo_your_kitchen = your_kitchen*3
print(triplo_your_kitchen)
print(dobro_my_kitchen < triplo_your_kitchen)

False
False
36.0
42.0
True


1)verifique quais elementos de my_house são maiores que 18.5 ou menores que 10.

2)Verifique quis elementos das mesmas posições dos arrays possuem valor menor que 11


In [48]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])
#my_house greater than 18.5 or smaller than 10
print(my_house[np.logical_or(my_house > 18.5, my_house < 10)])
# Both my_house and your_house smaller than 11
print(np.logical_and(my_house < 11, your_house < 11))

[20.   9.5]
[False False False  True]


In [51]:
z = 4
if z % 2 == 0:
  print(f"{z} é par")
else:
  print(f"{z} é impar")

4 é par


In [52]:
z = 3
if z % 2 == 0:
  print("z is divisible by 2")
elif z % 3 == 0:
  print("z is divisible by 3")
else:
  print("z is neither divisible by 2 nor by 3")

z is divisible by 3


1)na linha 10 verifique que se area for maior que 15 print a mensage : “Big PLace”

2)Apos á verificação, utilize o comando else para informar que se caso contrário, print “pretty small”.


In [53]:
#Define variables
room = "kit"
area = 14.0
# if statement for room
if room == "kit" :
  print("looking around in the kitchen.")
# if statement for area
if area > 15:
  print("Big place")
else:
  print("pretty small")

looking around in the kitchen.
pretty small
