<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/saulo_brito/pratique_05_de_julho.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random as rd

In [2]:
import numpy as np

In [3]:
height = range(150,210)

In [4]:
weight = range(50,150)

In [5]:
height = rd.sample(height,20)

In [6]:
weight = rd.sample(weight,20)

In [7]:
height_array = np.array(height) * 0.01

In [8]:
weight_array = np.array(weight)

In [9]:
bmi = weight_array / height_array ** 2

In [10]:
ligth = bmi < 21

In [11]:
print(ligth)

[False False  True False  True False False False False  True False False
  True False False False False False False False]


In [12]:
print(bmi[ligth])

[17.78970694 18.32242713 12.36235434 17.25      ]


In [13]:
print(weight_array[8:16])

[123  54 106 134  69  56  86 141]


In [14]:
print(height_array[11:20])

[1.9  2.   1.56 1.63 1.98 1.88 2.02 1.86 1.73]


In [15]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))

In [16]:
print(np_city)

[[ 1.48 70.39]
 [ 1.37 57.13]
 [ 1.74 67.35]
 ...
 [ 1.53 58.32]
 [ 2.02 65.82]
 [ 1.72 50.8 ]]
